### PR TITLE
Enable VMC standalone

### PR DESCRIPTION
**Pull request by benedikt-voelkel**

### CODE REVIEW

**Comment by benedikt-voelkel** [comment]
@sawenzel @ihrivnac @amorsch 

So that AliRoot can still be built with this https://github.com/alisw/alidist/pull/3640

**Comment by benedikt-voelkel** [comment]
Hello @amorsch can we test this?

**Comment by sawenzel** [comment]
+test

**Comment by amorsch** [comment]
+test

**Comment by benedikt-voelkel** [comment]
That looks a bit strange to me. I see no problems with the ROOT `--defaults release` built locally and actually it goes through including AliRoot including all tests
Is that a problem on the machine?
@TimoWilken maybe you can see something?

**Comment by benedikt-voelkel** [comment]
@pzhristov can we merge this as well? That should be the last bit before we can tackle alidist for real this time

**Pull request merged**
