### PR TITLE
ATO-410 - Possibility to register fitters and using Fit function with…

### PR DESCRIPTION
**Pull request by miranov25**
… similar inteface as in TH1::Fit

* AliTMinuitToolkit *  AliTMinuitToolkit::Fit(TH1* his, const char *fitterName, Option_t* option, Option_t* goption, Double_t xmin, Double_t xmax)

### CODE REVIEW

**Comment by miranov25** [comment]
Not sure what is expected to be done here.
Normally I had commit rights to the STAT directory. 
Is the review requered for each pull request?

**Comment by miranov25** [comment]
+1

**Comment by dberzano** [comment]
+test

**Comment by miranov25** [comment]
+1

**Comment by dberzano** [comment]
+1

@miranov25, you can't approve if you're not mentioned. I'll check the permissions because you indeed must have them for STAT, we must have missed something when migrating them.

**Pull request merged**
