### PR TITLE
ATO-83: improved error handling in TStatToolkit & AliTrending

### PR DESCRIPTION
**Pull request by sebaleh**
https://alice.its.cern.ch/jira/browse/ATO-83

### CODE REVIEW

**Comment by miranov25** [comment]
Hallo Dario.

I asked Sebastian to make pull request with his modification.  I assumed I should be able to approve it as he touched only my classes.

Marian.

**Comment by dberzano** [comment]
+1 (note that CERN is closed today)

**Comment by miranov25** [comment]
Hallo Dario.

I'm sorry. I was not exact. I wanted to test and review it before approving. Could you revert your decision before merged.

Thanks 
Marian.

**Comment by dberzano** [comment]
Only way is closing the PR. Please open a new one. And bear in mind once again that I am on vacation today and cannot fix any permission issue.

**Pull request closed without merging**
