### PR TITLE
Use the old ROOT default compression algorithm/level

### PR DESCRIPTION
**Pull request by mpuccio**
This should address the issue with the change of default compression algorithm in ROOT v6-14-00.
Do not merge until someone else besides me test it :)

### CODE REVIEW

**Comment by vpacik** [comment]
I have reproduced the issue with Streamer error. I can confirm, that after recompiling with this patch, error is gone and jobs are running smoothly.

**Comment by mpuccio** [comment]
Ciao @dberzano ,
actually the namespace ROOT:: is around since a while (even in ROOT5), and this is one of the cases where it was used even back then: it should compile with ROOT5.
Actually I was having issues with the merging of the output, but maybe it is related to my task. @vpacik  was the merging working for you?

Cheers,
Max

**Comment by vpacik** [comment]
Hi @mpuccio, @dberzano,

Actually, I have noticed that this inflates the output size quite dramatically (don't have exact number, but it is definitely more than factor 3). I have run merging now, and all jobs failed with validation error: e.g. (logs)[https://alimonitor.cern.ch/jobs/output.jsp?pid=1207196452&id=1207196452].

Cheers, V.

**Comment by mpuccio** [comment]
And here it goes, exactly what I was experiencing myself.
Modulo the size issue (we can increase the compression ratio), the trouble I see is:

> Warning in <TClass::TClass>: no dictionary for class ROOT::TIOFeatures is available
> Warning in <TClass::TClass>: no dictionary for class ROOT::Math::TRandomEngine is available
> Error in <TClass::New>: cannot create object of class TH2
> Error in <TClass::New>: cannot create object of class TH1
> Warning in <TClass::TClass>: no dictionary for class TF1Parameters is available

and this honestly I don't know how to fix. @dberzano ideas?

**Comment by dberzano** [comment]
I wish I did. Is this ROOT 5 trying to deserialize an object coming from ROOT 6?

**Comment by dberzano** [comment]
Note that I am uploading the logfile [here](https://github.com/alisw/AliRoot/files/2202053/stderr.txt) because otherwise it will be purged by AliEn.

**Comment by dberzano** [comment]
While we attempt to sort this out, we've reverted ROOT to v6-10-08, see alisw/alidist#1226.

**Comment by dberzano** [comment]
Merging as soon as we tag v5-09-36. This is scheduled for v5-09-37.

**Comment by dberzano** [comment]
+1

**Pull request merged**
