### PR TITLE
Sync AliGPU from O2

### PR DESCRIPTION
**Pull request by davidrohr**
@pzhristov : This should fix your problem with the gun test. Individual patch in O2 is here: AliceO2Group/AliceO2#2159

### CODE REVIEW

**Comment by davidrohr** [comment]
+test

**Comment by davidrohr** [comment]
+test

**Comment by pzhristov** [comment]
> @pzhristov : This should fix your problem with the gun test. Individual patch in O2 is here: [AliceO2Group/AliceO2#2159](https://github.com/AliceO2Group/AliceO2/pull/2159)

Yes, it does. I have just run successful test/gun on my Mac.

**Comment by pzhristov** [comment]
> Error while checking build/AliRoot/release for [5fcbb8c](https://github.com/alisw/AliRoot/commit/5fcbb8c304f489e258817429fda7ef6db0b39006):
> 
> ```
> 
> ```
> 
> Full log [here](https://ali-ci.cern.ch/repo/logs/alisw/AliRoot/971/5fcbb8c304f489e258817429fda7ef6db0b39006/build_AliRoot_release/fullLog.txt).

I do not see any error in the log file, something is wrong with the validation...

**Comment by davidrohr** [comment]
It should automatically rerun after some time. I think then it will pass.

**Comment by davidrohr** [comment]
+1

**Pull request merged**
