### PR TITLE
Initialization values for ZDC AOD TDC set when ESD TDC is not hit

### PR DESCRIPTION
**Pull request by coppedis**

### CODE REVIEW

**Comment by sawenzel** [comment]
@coppedis: Most of the changes seem to be whitespace fixes. Can you please indicate where to find the actual change?

**Comment by coppedis** [comment]
yes, I noticed it...unfortunately this must be an atom feature.
I attach here the output of git diff -w origin/master ANALYSIS/ESDfilter/AliAnalysisTaskESDfilter.cxx

diff --git a/ANALYSIS/ESDfilter/AliAnalysisTaskESDfilter.cxx b/ANALYSIS/ESDfilter/AliAnalysisTaskESDfilter.cxx
index 0c195e4..ba8488b 100644
--- a/ANALYSIS/ESDfilter/AliAnalysisTaskESDfilter.cxx
+++ b/ANALYSIS/ESDfilter/AliAnalysisTaskESDfilter.cxx
@@ -2143,6 +2143,7 @@ void AliAnalysisTaskESDfilter::ConvertZDC(const AliESDEvent& esd)
       }
     }
   }
+  else for(int i=0; i<4; i++)  zdcAOD->SetZNCTDCm(i, -999);
   if(esdZDC->IsZNAhit()){
     zdcAOD->SetZNAfired();
     int znach = esdZDC->GetZNATDCChannel();
@@ -2153,6 +2154,7 @@ void AliAnalysisTaskESDfilter::ConvertZDC(const AliESDEvent& esd)
       }
     }
   }
+  else for(int i=0; i<4; i++)  zdcAOD->SetZNATDCm(i, -999);
   if(esdZDC->IsZPChit()){
     zdcAOD->SetZPCfired();
     int zpcch = esdZDC->GetZPCTDCChannel();
@@ -2163,6 +2165,7 @@ void AliAnalysisTaskESDfilter::ConvertZDC(const AliESDEvent& esd)
       }
     }
   }
+  else for(int i=0; i<4; i++)  zdcAOD->SetZPCTDCm(i, -999);
   if(esdZDC->IsZPAhit()){
     zdcAOD->SetZPAfired();
     int zpach = esdZDC->GetZPATDCChannel();
@@ -2173,6 +2176,7 @@ void AliAnalysisTaskESDfilter::ConvertZDC(const AliESDEvent& esd)
        }
     }
   }
+  else for(int i=0; i<4; i++)  zdcAOD->SetZPATDCm(i, -999);
 }
 //______________________________________________________________________________

**Comment by mpuccio** [comment]
Hi, just for future reference: if you add ?w=1 to the github url you can see the actual changes only. 
In this case https://github.com/alisw/AliRoot/pull/280/files?w=1

**Comment by coppedis** [comment]
Thanks Max! :)

**Comment by sawenzel** [comment]
@mpuccio : This is indeed useful. 

We should still try to avoid excessive white space changes in commits. The problem is that now `git blame` will point to this commit on many lines which makes tracking the history of algorithmic changes harder. A hint from my side is to use `git add -p` and only commit things of real relevance.

**Comment by dberzano** [comment]
Hi @coppedis is there a JIRA ticket describing the issue?

**Comment by coppedis** [comment]
Dear @dberzano there is no JIRA ticket, I simply put also here an initialization value to be 100% sure that if there is no TDC value to be written in AOD we can easily identify the events.
Please, let me know if it is fine with you.

**Comment by dberzano** [comment]
Yes, I am not a ZDC expert :-)

I have one remark. `-999` is a "magic" value. Maybe it was better to have a constant set to `-999` to clarify this fact... can you do that?

**Comment by dberzano** [comment]
+1 many thanks for the prompt reaction!

**Comment by coppedis** [comment]
Thanks to you for your useful suggestions! (btw there were other 999 in the same class ;) )

**Pull request merged**
