### PR TITLE
Service Task Commits: Implementation of Different Charges in TRD Parameters

### PR DESCRIPTION
**Pull request by jluehder**

### CODE REVIEW

**Comment by shahor02** [comment]
+test

**Comment by chiarazampolli** [comment]
+test

**Comment by chiarazampolli** [comment]
Hello @jluehder 
Can you have a look at the error?

Cheers,
Chiara

**Comment by shahor02** [comment]
Hi @jluehder 

Changing int to Int_t will not help: the default initialization of the data members in the class declaration is allowed only from c++11, and the build did not like that. You have to move the initialization to constructor...

**Comment by shahor02** [comment]
+test

**Comment by shahor02** [comment]
+test

**Comment by tdietel** [comment]
Hello,

I had a look throught the code, and it seems ok to me. Please go ahead with the merging.

Cheers,
 - Tom.

**Comment by shahor02** [comment]
+1

**Pull request merged**
