### PR TITLE
implement new variables for NanoAOD

### PR DESCRIPTION
**Pull request by lhusova**
Implement some missing variables for NanoAODs

### CODE REVIEW

**Comment by mazimm** [comment]
I was involved in this development and we want to push these first general developments to AliRoot so that they are available for all users of NanoAODs.  Could someone with the rights approve it?

**Comment by shahor02** [comment]
+test

**Comment by shahor02** [comment]
@lhusova : can you modify the code to avoid c+11 extensions, just using ````for (int i=21;i--;) fcovmat[i]=-1; ````

**Comment by mazimm** [comment]
This commit should be included in AliRoot at the same time as another commit in AliPhysics. Please do not accept this commit earlier.

**Comment by shahor02** [comment]
+test

**Comment by shahor02** [comment]
@mazimm, @lhusova : concerning the comment https://github.com/alisw/AliRoot/pull/367#issuecomment-322757699 : what about aliphysics commit?

**Comment by lhusova** [comment]
@shahor02 The AliPhysics commit is already there, but not approved yet

**Comment by shahor02** [comment]
@lusova : I see from https://github.com/alisw/AliPhysics/pull/2223#issuecomment-322766560 that @dberzano is taking care of this, so better he merges both PRs at the same time

**Comment by dberzano** [comment]
Yes indeed.

**Comment by dberzano** [comment]
Hi, all tests are green, meaning that the problem was temporary and it cleared out automatically. You can safely ignore it.

**Comment by dberzano** [comment]
+1
See also alisw/AliPhysics#2223

**Pull request merged**
