### PR TITLE
Change SPD cooling pipes material from Inox to Phynox

### PR DESCRIPTION
**Pull request by mario6829**
The SPD cooling pipe material was changed from Inox to Phynox (as it should be), in order to check whether this correction improves the material budget comparison between data and MC.

### CODE REVIEW

**Comment by fprino** [comment]
+1

**Comment by chiarazampolli** [comment]
Hello @ktf , 

Can you merge this PR?

Cheers,

Chiara

**Comment by davidrohr** [comment]
hm, why aren't the tests running?

**Comment by davidrohr** [comment]
+1

**Comment by chiarazampolli** [comment]
> hm, why aren't the tests running?

Because the PR is not on master... And in this case, the automatic testing is disabled.

**Pull request merged**
