### PR TITLE
Adding D meson to D meson resonance swap option

### PR DESCRIPTION
**Pull request by stefanopolitano**
This PR add possibility to swap D mesons with D meson resonances

### CODE REVIEW

**Comment by gconesab** [comment]
Hi, for wich production is this needed and to which aliroot tag should be ported to?

**Comment by fgrosa** [comment]
> Hi, for which production is this needed and to which aliroot tag should be ported to? An HF expert should comment on the changes, that look fine to me.

Hi @gconesab, this is needed for a MC production anchored to pass2 pp@13 TeV (2016, 2017, 2018) data samples. The productions are not yet requested at the PB (we presented last week in the PAG https://indico.cern.ch/event/1280320/contributions/5401175/attachments/2646244/4580556/DsReso_pp13TeV2023May12.pdf). I am not sure whether they will be asked this week or lately (maybe @lvermunt, @fcatalan92, @fcolamar, @ginnocen can tell you more). I can say that we tested it with @stefanopolitano and it did work properly.

**Comment by fcolamar** [comment]
Ciao @gconesab, all,
for HF this PR is ok, thanks Fabrizio!
We can indeed ask for the MC already next week (this week there's no PB), if we get the final estimates for the 'validation-only' options, less resource-consuming, as discussed in the PAG. But this we can discuss in another place.
Cheers,
Fabio

**Comment by lvermunt** [comment]
Hi all, the MC request this PR belongs to was approved in the PB (of 25/05, see https://alice.its.cern.ch/jira/browse/ALIROOT-8847). Can this PR be approved please? Thanks!

**Comment by ktf** [comment]
+test

**Comment by fgrosa** [comment]
Hi @chiarazampolli could you please have a look and check if it is fine with you? Thank you very much!

**Comment by chiarazampolli** [comment]
+1

**Pull request merged**
