### PR TITLE
Implement missing treatment of applyEtaCorrection and applyMultiplici…

### PR DESCRIPTION
**Pull request by wiechula**
…tyCorrection

### CODE REVIEW

**Comment by chiarazampolli** [comment]
+1

**Comment by chiarazampolli** [comment]
Hello @ktf , @MichaelLettrich .
I am not sure I understand: the error above is real or not? The build/AliRoot/release test was passed and the log points at that. 
Thanks!
Chiara

**Comment by chiarazampolli** [comment]
+1

**Comment by chiarazampolli** [comment]
Hello @ktf, @MichaelLettrich , 
macos still appears...
Chiara

**Comment by MichaelLettrich** [comment]
@chiarazampolli  thanks for reporting. I have to check this with @ktf. I am out of ideas why this appears, it definitely should not :/

**Pull request merged**
