### PR TITLE
Account for BC dependent ALTRO/LHC clocks shift (#1099)

### PR DESCRIPTION
**Pull request by chiarazampolli**
See discussion at https://alice.its.cern.ch/jira/browse/ALIROOT-8260?focusedCommentId=242160&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-242160
for details.
Pinging @shahor02 , @miranov25 , @fprino , @catalinristea

### CODE REVIEW

**Comment by chiarazampolli** [comment]
Hello @ktf , 

here it is, for the new tag from 53-patches.

Chiara

**Comment by ktf** [comment]
+test

**Comment by MarekKowalski1504** [comment]
+1

**Comment by chiarazampolli** [comment]
Hello @MarekKowalski1504 , 

The PR was already merged in the branch v5-09-53-patches. You need to cherry pick it to the "itsgeom" branch too. 

Chiara

**Pull request merged**
