### PR TITLE
[EMCAL-39, ALIROOT-7708] Check for active TRU

### PR DESCRIPTION
**Pull request by mfasDa**
Implement check of the TRU status based on the status in
the STU region.

### CODE REVIEW

**Comment by mfasDa** [comment]
This is a helper function used to check whether a TRU was active in a given run or not. Used to fix a crash reported in ALIROOT-7708, crashing in simulation for a TRU which was dead in the given run due to 0-value for L0 threshold.

**Comment by mfasDa** [comment]
+1

New function, not changing existing logics. Safe to merge!

**Comment by chiarazampolli** [comment]
Hello,

I guess this error is temporary. @dberzano @ktf , can you confirm?

Chiara

**Comment by ktf** [comment]
Looks like the mac builds are currently down. I guess the CERN network outage of today is still affecting that. Merging this.

**Pull request merged**
