### PR TITLE
Fix ROOT 6 headers problem in HOMER

### PR DESCRIPTION
**Pull request by dberzano**
Complements #757

### CODE REVIEW

**Comment by dberzano** [comment]
@davidrohr fyi

**Comment by davidrohr** [comment]
+test OK, let's see if that compiles... not sure about that key_t type, seems to be not a standard type, so depends on the compiler...

**Comment by davidrohr** [comment]
@dberzano : i tried something similar in alisw/AliRoot#766 and compilation fails on some compilers because of stupid key_t type. But perhaps your patch works as it leaves limits.h in. If not, I am working on a more general fix.

**Comment by dberzano** [comment]
+1

**Comment by davidrohr** [comment]
@dberzano : Your PR fails for the same reason as mine alisw/AliRoot#766 :|
I think I'll have a "proper" fix soon...

**Comment by dberzano** [comment]
@davidrohr for the record we've got a Skype chat open, lol

**Comment by dberzano** [comment]
@davidrohr OK I didn't realize you have opened #766, sorry! 😄 

I'll let you fix it then! Many thanks!

**Pull request closed without merging**
