### PR TITLE
New DPMJET version fixes

### PR DESCRIPTION
**Pull request by gconesab**

### CODE REVIEW

**Comment by gconesab** [comment]
Some tests are still ongoing by Andreas so we may want to wait the merge till done.

**Comment by pzhristov** [comment]
No need to make a single PR - the fixes can be merged when available.

**Comment by gconesab** [comment]
Andreas just confirmed  at the PB the new DPMJET is operational, I think we can merge.  I saw another commit by @pzhristov  related to DPMJET but seemed just test macros, so I guess not need to port.

**Comment by gconesab** [comment]
Ciao @chiarazampolli, @pzhristov  or any other, can you approve?
Thanks ... Gustavo

**Comment by chiarazampolli** [comment]
Since Peter is away, I am approving. 
+1

**Comment by chiarazampolli** [comment]
Hi @gconesab , does this go only to 56-patches?

**Comment by chiarazampolli** [comment]
+1

**Comment by gconesab** [comment]
Yes, the request is for pass2 anchored data MC productions so this only applies to 56 as far as I understand it.

**Comment by chiarazampolli** [comment]
Hi, 

Since this is to be merged to v5-09-56-patches and not master, I am not sure the tests will run. @TimoWilken , @ktf , can you confirm? In the past, one had to merge by hand, is it still the case?

Chiara

**Comment by chiarazampolli** [comment]
> Yes, the request is for pass2 anchored data MC productions so this only applies to 56 as far as I understand it.

Ok, but don't we want it also for master?

Chiara

**Comment by gconesab** [comment]
> > Yes, the request is for pass2 anchored data MC productions so this only applies to 56 as far as I understand it.
> 
> Ok, but don't we want it also for master?
> 
> Chiara

I do not understand, this is a port form master

**Comment by TimoWilken** [comment]
> Since this is to be merged to v5-09-56-patches and not master, I am not sure the tests will run. @TimoWilken , @ktf , can you confirm? In the past, one had to merge by hand, is it still the case?

Hi Chiara, you're correct, the tests will not run for this PR. You'll have to merge by hand.

**Comment by chiarazampolli** [comment]
Ciao @gconesab ,

ok thanks, i did not remember the commit in master, and saw the comment about testing here, sorry.

Now i merged it.

Cheers,

Chiara

**Pull request merged**
