### PR TITLE
Updating ZEM position and adding covers.

### PR DESCRIPTION
**Pull request by ecalvovi**

### CODE REVIEW

**Comment by pzhristov** [comment]
Hi @ecalvovi, did you check for possible overlaps?

**Comment by pzhristov** [comment]
+test

**Comment by ecalvovi** [comment]
Hi @pzhristov. Yes this was tested and there are no overlaps after a commit by Andreas Morsch modifying an air volume in AliPIPEv3.cxx (https://github.com/alisw/AliRoot/pull/339)

**Comment by pzhristov** [comment]
+1

**Pull request merged**
