### PR TITLE
[ALIROOT-8358]: Update galice.cuts

### PR DESCRIPTION
**Pull request by chiarazampolli**
Switching on delta-ray production inside V0 scintillators.

### CODE REVIEW

**Comment by shahor02** [comment]
+1

**Comment by chiarazampolli** [comment]
Hello @shahor02 ,

Also here, thanks for approving, but we need "brute force merging" by @ktf , as this is not master...

Chiara

**Comment by shahor02** [comment]
ok, ok, I will stop +ing...

**Comment by chiarazampolli** [comment]
you were very nice, actually, i really appreciated.
Chiara

**Pull request merged**
