### PR TITLE
Use OCDB values to simulate the luminous region width in x and y

### PR DESCRIPTION
**Pull request by fprino**

### CODE REVIEW

**Comment by dberzano** [comment]
+test @fprino was this discussed somewhere, who can determine if this change is OK?

**Comment by fprino** [comment]
Hi Dario,

it was discussed and agreed in the calib and tracking meeting of today.
@chiarazampolli and @shahor02 will also have a look at this change in the code.

Francesco

**Comment by dberzano** [comment]
OK thanks (I had no doubts but I had to ask!), let's have @chiarazampolli and/or @shahor02 `+1` this PR.

**Comment by shahor02** [comment]
+1

**Pull request merged**
