### PR TITLE
Massive renaming of AliVParticle label getters

### PR DESCRIPTION
**Pull request by shahor02**
Do not approve merging, it should be done by @dberzano at the tagging time

### CODE REVIEW

**Comment by shahor02** [comment]
+test

**Comment by shahor02** [comment]
https://alice.its.cern.ch/jira/browse/ALIROOT-8218?filter=-2

**Comment by shahor02** [comment]
+test

don't merge (except when tagging by Dario)

**Comment by dberzano** [comment]
+1

**Pull request merged**
