### PR TITLE
Sync AliGPU from O2 (0594279c8bc061d45d79388dc1aad723652fc6a6)

### PR DESCRIPTION
**Pull request by davidrohr**

### CODE REVIEW

**Comment by davidrohr** [comment]
+test

**Comment by davidrohr** [comment]
+test

**Comment by davidrohr** [comment]
+test

**Comment by davidrohr** [comment]
@pzhristov @ktf @chiarazampolli : Can it be that the MacOS CI is generally broken? I don't see how the error could be related to my PR, and also other PRs have been failing in build/AliRoot/macos.

**Comment by chiarazampolli** [comment]
Ciao @davidrohr , 

Before the Xmas break, there were issues with the MacOS CI, but I think that @MichaelLettrich said they were fixed (or about to be fixed). He can maybe comment.

Chiara

**Comment by davidrohr** [comment]
@MichaelLettrich @ktf : Did you have time to look at the python problem for the MacOS CI?

**Comment by ktf** [comment]
yes, we need https://github.com/alisw/alidist/pull/1976 to be merged, but since it might affect analysis builds I still need to cross check everything is ok.

**Comment by davidrohr** [comment]
ok, thx, it is not so urgent for me.

**Comment by ktf** [comment]
The fix is in principle there. Checking again.

**Comment by davidrohr** [comment]
+test

**Comment by davidrohr** [comment]
+test

**Comment by ktf** [comment]
So with @chiarazampolli we came to the conclusion that the error is actually a setup issue on the new macOS builder, which needs to be understood, together with @MichaelLettrich. I am merging this, since AliRoot compiles fine.

**Pull request merged**
