### PR TITLE
Add kLcLpi forced decay option to AliDecayer

### PR DESCRIPTION
**Pull request by jezwilkinson**
Adds option to AliDecayerPythia and AliDecayerPythia8 to force Lambda_c to decay in the Lambda pion channel (3122 211), for use in dedicated MC productions.

### CODE REVIEW

**Comment by jezwilkinson** [comment]
Hello @davidrohr @maireiphc @qgp @jgrosseo @shahor02 @sawenzel @chiarazampolli @ktf @pzhristov , could this PR please be looked at and reviewed? We plan to make an MC request soon that depends on having this commit in the tag. It has been tested locally and the new decay option works as expected along with the new custom generator option that was merged to AliDPG.
Thanks
--Jeremy

**Comment by chiarazampolli** [comment]
+test

**Comment by chiarazampolli** [comment]
Hi @jezwilkinson , 

I "+test"-ed, but I have not the rights for all folders that you changed at the moment. @shahor02 , can you give a "+test" too?

Chiara

**Comment by ktf** [comment]
+1

**Comment by jezwilkinson** [comment]
@ktf The build test for AliRoot/release is now saying that there is a merge conflict where i wasn't seeing any before - I'm not sure what exactly this means, is there something to fix on my end?

**Pull request merged**
