### PR TITLE
Prefer Clear over Delete for `AliESDTRDTracklet`s

### PR DESCRIPTION
**Pull request by ktf**
This is where we spend 80% of the cost when iterating on an ESD collection.

### CODE REVIEW

**Comment by ktf** [comment]
@shahor02 @pzhristov am I missing something trivial?

**Comment by shahor02** [comment]
@ktf No, it should be ok to use Clear. In fact, one even does not need to use Clear("C"), just Clear() should be enough since the tracklets don't allocate memory.

**Comment by ktf** [comment]
Ok, adapted to use `Clear()`.

**Comment by ktf** [comment]
+test

**Comment by shahor02** [comment]
+1

**Pull request merged**
