### PR TITLE
v5-09-54-patches fis bug fixes: phi range now in correct units, and

### PR DESCRIPTION
**Pull request by gconesab**
- momentum distributions for Fermi motion are now flat

### CODE REVIEW

**Comment by gconesab** [comment]
Hi @TimoWilken, can you merge? Needed for  ALIROOT-8862. Thanks

**Comment by gconesab** [comment]
In case Timo is not anymore responsible of this, can maybe @chiarazampolli or @pzhristov try to merge this so that we can tag?

**Comment by chiarazampolli** [comment]
+1

**Comment by gconesab** [comment]
Hello, can anyone try brute-force merging?

**Comment by alcaliva** [comment]
@chiarazampolli  :)

**Comment by ktf** [comment]
+test

**Comment by gconesab** [comment]
The tests do not start, we really need to merge this by hand or fix the testing machinery. This worked on master, I would not expect this to fail on the tag.

**Comment by chiarazampolli** [comment]
Done!

**Pull request merged**
