### PR TITLE
Usage of the CSS style  +QA development

### PR DESCRIPTION
**Pull request by miranov25**
## QA and perfromance parameterization development
Contributors: Marian, Boris , Sebastian

### Add CSS style for root graphics and graphics
* **AliDrawStyle (EXTENDED)**, **AliDrawStyleTest.C(EXTENDED)**  + test **test/*.css files (NEW)**
  *  implementing subset of CSS style standard as in html
  * see doxygen documentation, resp. usage in the test/AliDrawStyleTest.C
     * usage in the AliPhysics_ROOT QA macros
  * author: Boris, Marian   
* **AliPainter (NEW)** 
  * using CSS style
  * for QA and performance plots generation
  * implementing object drawing using string formatting see
  * Status: Work in progress - more painting functions to be added 
  * E.g. ND Histogram draw interface (see doxygen) as serie of functors
     ````
     AliPainter::DrawHistogram("hisK0DMassQPtTgl()(0)()(err)", hisArray);
     AliPainter::DrawHistogram("hisK0DMassQPtTgl(-0.02,0.02)(0)(1)(err)", hisArray);
     ````      
  * author: Boris, Marian
* **AliTreeTrending (EXTENDED)**
  * Update of class to create QA reports
  * Using CSS style
  * Add more function - eg. to create decomposed status plot
  * author: Marian, Sebastian
* **STAT/TStatToolkit.h(EXTENDED)**
  * Adding function for the "sparse" graphs merging/rebinning 
    * Used in AliTreeTrending or user macros 
  ````
      void RebinSparseGraph(TGraph * graph0, TGraph *graph1, Option_t * option="");
      void RebinSparseMultiGraph(TMultiGraph *multiGraph, TGraph *graphRef);
      void MakeMultiGraphSparse(TMultiGraph *multiGraph);
  ````

### ROOT tree "database" access
* **AliExternalInfo (EXTENDED)**
  * Implementing GetChain with friend trees (similar as GetTree)
    ```` 
    AliExternalInfo::GetChain(TString type, TString period, TString pass, TString friendList)
    ````
  * Used for the calibration and reconstruction  QA validation (in AliPhysics) for multi periods
*  STAT/Macros/aliExternalInfo.C
  * Example usage of the AliExternalInfo class 
  * Functions usefull also for combined root tree "DB" queries (see doxygen documentation)
  * Example usage for correlating Logbook, QA.TPC, QA.EVS:
  ````
    .L $AliRoot_SRC/STAT/Macros/aliExternalInfo.C
    drawLogbook("LHC15o","pass1","QA.TPC.meanTPCncl>0","runDuration:totalEventsPhysics:totalNumberOfFilesMigrated:MonALISA.RCT.tpc_value");
    drawLogbook("LHC10h","pass2","totalEventsPhysics>1000&&totalNumberOfFilesMigrated>20","runDuration:totalEventsPhysics:totalNumberOfFilesMigrated:MonALISA.RCT.tpc_value");
    drawLogbook("LHC11h","pass2","totalEventsPhysics>1000&&totalNumberOfFilesMigrated>20","runDuration:totalEventsPhysics:totalNumberOfFilesMigrated:MonALISA.RCT.tpc_value");
  ````
### HTML table export
* **AliTreePlayer(UPDATED)** - **AliTreeFormulaF(NEW, derived from TTreeFormula)**
  * Usage of string formatted TTree queries (not possible in TTreefromula)
    * See example fromat string used in html table export to format html link
    ````
    TString pathData="<a href=\"http://aliqatpc.web.cern.ch/aliqatpc/data/%d{TPC.Anchor.year}/%s{TPC.Anchor.period.GetName()}/%{TPC.Anchor.pass.GetName()}/000%d{run}/";
    ````
### Fitting procedure    
* **STAT/AliTMinuitToolkit.h (Extended)**
  * export with formula as a latex formula - used for legends)
  * Used in the QAs plots for fits description
   
### Makefiles, tests  and doxygen
* STAT/CMakeLists.txt
  * Added new classes
* doxygen/Doxyfile.in
  * adding test and Macros to doxygen
*  STAT/test/statTest.sh
  * updated tests 
* STAT/STATLinkDef.h  
 * new classes
 * adding CINT interace for some map

### CODE REVIEW

**Comment by miranov25** [comment]
+test

**Comment by pzhristov** [comment]
+1

**Comment by miranov25** [comment]
Commit:
https://github.com/alisw/AliRoot/pull/496/commits/a4602ce296ab0877e423d67996e3d8cea657bf06
most probably fix the problem at el6native.
I can not test it.
I tested builds ROOT5 and ROOT6 on 2 platforms.

**Comment by miranov25** [comment]
+test

**Comment by dberzano** [comment]
+1 Thanks for the fix, we'll see if it works! Will be merged automatically if it does.

**Pull request merged**
