### PR TITLE
Added function in AliGenHijing to change Pz sign

### PR DESCRIPTION
**Pull request by rihanphys**
Added a function in AliGenHijing to (optionally) change Pz sign.

### CODE REVIEW

**Comment by rihanphys** [comment]
I added a  function SetFlipTrackPz(Bool_t b) with Boolean argument in the AliGenHijing class to (optionally) change the sign of Pz of the primary tracks. This is needed to simulate fixed target collisions for the ALICE Fixed Target program. In the LAB frame, the projectile is moving in the +ve Z direction while target is fixed. This causes the produced particle to be boosted in the forward rapidity (+ve eta).  However, for the fixed target simulation in ALICE, we place the target at +480m and the projectile should be moving in -ve Z direction. So that the particle are boosted in the -ve eta region where we would have our tracking detectors (in the MC simulation). The simplest way to obtain this is to change the direction of Pz for primary tracks. Hence the function is added. 

Important Note : By default the Boolean is set to kFALSE, hence the track Pz sign is NOT changed. Therefore this change does not affect any existing/or future analysis with the class in its nominal settings.

**Comment by rihanphys** [comment]
I added a  function SetFlipTrackPz(Bool_t b) with Boolean argument in the AliGenHijing class to (optionally) change the sign of Pz of the primary tracks. This is needed to simulate fixed target collisions for the ALICE Fixed Target program. In the LAB frame, the projectile is moving in the +ve Z direction while target is fixed. This causes the produced particle to be boosted in the forward rapidity (+ve eta).  However, for the fixed target simulation in ALICE, we place the target at +480m and the projectile should be moving in -ve Z direction. So that the particle are boosted in the -ve eta region where we would have our tracking detectors (in the MC simulation). The simplest way to obtain this is to change the direction of Pz for primary tracks. Hence the function is added. 

Important Note : By default the Boolean is set to kFALSE, hence the track Pz sign is NOT changed. Therefore this change does not affect any existing/or future analysis with the class in its nominal settings.

**Comment by chiarazampolli** [comment]
Looks ok to me. @amorsch , could you also check?

Thanks!

Chiara

**Comment by amorsch** [comment]
> Looks ok to me. @amorsch , could you also check?
> 
> Thanks!
> 
> Chiara

Indeed, looks ok.
Cheers
Andreas

**Comment by chiarazampolli** [comment]
+1

**Comment by chiarazampolli** [comment]
Thanks @amorsch !
@rihanphys , note that to use this on the grid, or with CVMFS, you need a new AliRoot tag. Is it urgent? 

Chiara

**Comment by rihanphys** [comment]
@chiarazampolli, I managed to run the simulation for run3 with the changes to AliGenHijing locally in my laptop. Therefore, it is not so urgent to have a new AliRoot tag.  However, I see some error in the merging. I have to check if that is originating from my changes.

**Comment by chiarazampolli** [comment]
Hello @rihanphys ,

The error does not depend on your changes. I pinged already @ktf  and @MichaelLettrich on a PR with the same issue.

Chiara

**Comment by ktf** [comment]
@ihrivnac I suspect your changes for geant4 broke the gun test. Could you have a look?

**Comment by ihrivnac** [comment]
The errors are reported also for ROOT libraries:

```
calling rungen.sh
Error in <TSystem::ExpandFileName>: input: $ROOT_DYN_PATH/libRIO, output: $ROOT_DYN_PATH/libRIO
Error in <TSystem::ExpandFileName>: input: $ROOT_DYN_PATH/libCling, output: $ROOT_DYN_PATH/libCling
Error in <TSystem::ExpandFileName>: input: $ROOT_DYN_PATH/libSTEER, output: $ROOT_DYN_PATH/libSTEER

```
But let's try to revert my last update and see if it helps.

**Pull request merged**
