### PR TITLE
STARLIGHT update (svn revision 286)

### PR DESCRIPTION
**Pull request by hcab14**

### CODE REVIEW

**Comment by chiarazampolli** [comment]
Hello Christoph,

Please, note that if you need to use this in production, you should also open a JIRA ticket (Production request) for this (once merged).

Chiara

**Comment by rbertens** [comment]
+test 
@qgp  , could you also take a look?

**Comment by hcab14** [comment]
Hi @rbertens,

it is an update from the STARLIGHT svn which adds more detailed printout on the cross section calculation but is not supposed to change the actual output. This is not my code/svn, (one of) the main author(s) of STARLIGHT is Joakim Nystrand.

Cheers
Christoph

**Comment by hcab14** [comment]
Hi all,

I meant to add an explanation for 61193d4 in a pull request, but it got merged with this pull request:
- this kind of problem has first been seen and corrected for in AD reconstruction
- basically, the TTree (AD/Calib/Saturation) needs to know what type of object the TClonesArray branches contain
- this is why the TClonesArray branches need to be properly initialized

Cheers
Christoph

**Comment by ecalvovi** [comment]
+1

**Comment by gconesab** [comment]
Hello, can this PR contain just what was changed and not what was already comitted? It is impossible to know if it was touched EMCal code or it is just a merge of a previous commit.

**Comment by rbertens** [comment]
HI @hcab14 ,
If you reopen the initial PR i'll +1 a.s.a.p.
my best,
redmer

**Comment by hcab14** [comment]
Thank you @rbertens. I had performed a git pull --rebase origin master in between pushing my commits to my remote git repository and I guess this is why all the other commits were showing up in this PR.

As you have seem I have now opened a new PR https://github.com/alisw/AliRoot/pull/302

Cheers
Christoph

**Pull request closed without merging**
