### PR TITLE
PWGPP-592 - AliOCDBtoolkit::DumpOCDB - TGrid::Connect if alien:// file requested

### PR DESCRIPTION
**Pull request by miranov25**
# Example usage described in JIRA:
https://alice.its.cern.ch/jira/browse/ALIROOT-8420?focusedCommentId=248871&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-248871

### CODE REVIEW

**Comment by miranov25** [comment]
+test

**Comment by chiarazampolli** [comment]
+test

**Comment by ktf** [comment]
+test

**Comment by miranov25** [comment]
+1

**Comment by chiarazampolli** [comment]
+1

**Comment by miranov25** [comment]
+1

**Comment by miranov25** [comment]
Hello.
Could some approved ? We need that for the TPCdEdx correction.
Marian

**Comment by shahor02** [comment]
+1

**Comment by miranov25** [comment]
Test did not start since 2 days.  looks like Build server not working

**Comment by chiarazampolli** [comment]
Hello @ktf, could you have a look?

**Comment by ktf** [comment]
+1

**Pull request merged**
