### PR TITLE
Add option for semileptonic decay of Xic0

### PR DESCRIPTION
**Pull request by fgrosa**
Add option to force Xic0 -> Xi- e+ nu_e decay instead of Xic0 -> Xi- pi+ decay, needed for D2H MC productions

### CODE REVIEW

**Comment by fgrosa** [comment]
@chiarazampolli could you maybe have a look at this PR? It is also related to this other PR in AliDPG https://github.com/alisw/AliDPG/pull/412 for forcing the Xic0 to decay in the semileptonic decay channel that we study in the D2H. Thanks a lot!

**Comment by chiarazampolli** [comment]
+1

**Comment by chiarazampolli** [comment]
Ciao @fgrosa , 

It looks fine to me, approved.

Chiara

**Comment by fgrosa** [comment]
> Ciao @fgrosa ,
> 
> It looks fine to me, approved. Note that if you need this for some old tag, we need to cherry pick this commit.
> 
> Chiara

Ciao @chiarazampolli,
Thanks a lot! Yes indeed we will ask to backport this commit to the AliRoot tag used for the productions, thanks for the reminder!
Cheers, Fabrizio

**Pull request merged**
