### PR TITLE
PWGPP-571 Adding TOF debug streamers+IonTail time scaling 

### PR DESCRIPTION
**Pull request by miranov25**

### CODE REVIEW

**Comment by miranov25** [comment]
* merged usage of TOF streamers to the master
* swith to enable ion tail time scaling

**Comment by shahor02** [comment]
+1

**Comment by pzhristov** [comment]
Hi @shahor02 @miranov25, I merged the previous pull requests and now we have a conflict. Would you resolve it? Then I will merge the result.

Thanks,
Peter

**Comment by chiarazampolli** [comment]
Hello @miranov25 , 

One question: this is still not the PR we discussed concerning the error parameterization, right? Unless I misunderstood, for me the ion tail WON'T be enabled for pass2, and the only changes that we might take are those for the error parameterization (and maybe TOF SetUse).

Chiara

PS. Pinging @fprino .

**Comment by fprino** [comment]
Hi Marian,

if I am not mistaken, you added a new data member in AliTPCRecoParam.h and you did not increase the class revision number. This might create problems with the root streamer.
Can you please check?

Thanks!
 Ciao, Francesco

**Comment by miranov25** [comment]
I increased class version and resolved conflict

**Comment by miranov25** [comment]
The next commits are in the queue:
* TPC error param - modifying now
* For TOF SetUse I have to have production done before commit


-

**Comment by ktf** [comment]
+1

**Pull request merged**
