### PR TITLE
Fixes for Doxygen HTML reference documentation:

### PR DESCRIPTION
**Pull request by cholmcc**
- Protect the ClassDef and ClassImp macros so we get less warnings
  from these macros.
- Warn if things are not documented
- Be quite
- Add custom stylesheet that makes the output look more along the
  lines of the "corporate brand" charter given at aliweb.cern.ch/charter. 
 For an example, see 
    http://alice-rivet.cern.ch/
This works for all Doxygen version

### CODE REVIEW

**Comment by dberzano** [comment]
Hi @cholmcc, please use some decency when writing commit messages. This PR cannot be approved as it is. Let me quote our [guide](http://alisw.github.io/git-tutorial/):

> Notice GitHub is a popular, public, hosting site, so there will be zero tolerance for offending 
 statements or embarrassments to ALICE collaboration. In case of doubt, you can find more information in the commit guidelines.

**Comment by pzhristov** [comment]
Hi @dberzano,

Should we merge this pull request?

**Comment by dberzano** [comment]
@pzhristov please hold it, I have actually wanted to factor things out before proceeding and haven't had time to have a look at it yet.

**Comment by dberzano** [comment]
Closing - I have picked what we need and opened #360.

**Pull request closed without merging**
