### PR TITLE
Moving STAT-dependent classes from STEERBase to STAT

### PR DESCRIPTION
**Pull request by pzhristov**
This is the first part of the changes - the second one is to make STAT independent from STEERBase.

### CODE REVIEW

**Comment by pzhristov** [comment]
+test

**Comment by pzhristov** [comment]
+test

**Comment by dberzano** [comment]
Makes sense to me!

**Comment by dberzano** [comment]
Hi @pzhristov I believe our DA RPM generation is now broken ([check the logs](https://alijenkins.cern.ch/job/DAQ/job/daq-da-rpms/738/console)) because of this PR, can you have a look?

**Comment by pzhristov** [comment]
The RPM build should not be affected if I added correctly the include directories to all needed CMakeLists.txt. Yesterday I did not detect any issue, but may be the partial build did not detect some dependencies. I am running a build from scratch to see if this is the case.

**Pull request merged**
