### PR TITLE
AliMC: volume-to-module map; deterministic event seeding

### PR DESCRIPTION
**Pull request by sawenzel**
* Simulation now writes a text file containing a mapping
  of logical volume names to the module that owns them;
  This is needed for accounting of MC steps to modules (as done
  in the MCStepLogger and related analysis)

* Adding an option to achieve reproducible/deterministic event sequence
  when setting a special environment variable. This is a useful and painless way
  to achieve same event sequence for G3 and G4 productions, for instance.

### CODE REVIEW

**Comment by sawenzel** [comment]
+test

**Comment by sawenzel** [comment]
+test

**Comment by sawenzel** [comment]
+test

**Comment by shahor02** [comment]
+1

**Comment by dberzano** [comment]
@sawenzel the tests do run the gun tests, both on macOS and Linux. I have checked.

**Comment by sawenzel** [comment]
@dberzano : This is not evident to me. I can't see this in the logs. Would the system report it if the gun test failed?

**Comment by dberzano** [comment]
If the guntest fails, the logfile will be displayed and a link to the logfile will be present, as for any other package, so yes.

**Comment by sawenzel** [comment]
Ok. Thanks for the info.

**Pull request merged**
