### PR TITLE
Sync AliGPU from O2 (Integration of AliTPCCommon into AliRoot)

### PR DESCRIPTION
**Pull request by davidrohr**
See AliceO2Group/AliceO2#1747
This is a first test to find and fix errors for MacOS / ROOT5 via the CI.

### CODE REVIEW

**Comment by davidrohr** [comment]
+test

**Comment by davidrohr** [comment]
+test
Kind Regards
David Rohr

(Sent from my mobile, excuse the typos.)

**Comment by davidrohr** [comment]
+test

**Comment by davidrohr** [comment]
+test

**Comment by davidrohr** [comment]
+test

**Comment by davidrohr** [comment]
+test

**Comment by davidrohr** [comment]
+test

**Comment by davidrohr** [comment]
+test

**Comment by davidrohr** [comment]
+test

**Comment by davidrohr** [comment]
+test

**Comment by davidrohr** [comment]
+test
Kind Regards
David Rohr

(Sent from my mobile, excuse the typos.)

**Comment by davidrohr** [comment]
+test

**Comment by davidrohr** [comment]
+test

**Comment by davidrohr** [comment]
+test

**Comment by davidrohr** [comment]
+test

**Comment by davidrohr** [comment]
+test

**Comment by dberzano** [comment]
+test

**Comment by dberzano** [comment]
@davidrohr you'll be able to approve it yourself from the next round

**Comment by davidrohr** [comment]
+test

**Comment by davidrohr** [comment]
@dberzano : Why do we sometimes get these build error messages by alibuild, even though the build passed?

**Comment by dberzano** [comment]
@davidrohr sometimes there are glitches for various reasons (maybe the worker was restarted). What matters in the end is the green status.

**Comment by dberzano** [comment]
+1 this part passed the release validation. Merging.

**Pull request merged**
