### PR TITLE
Added Sexaquark

### PR DESCRIPTION
**Pull request by alcaliva**

### CODE REVIEW

**Comment by gconesab** [comment]
Hi @amorsch, is this commit ok?
if so, @chiarazampolli can you merge?
Thanks

**Comment by amorsch** [comment]
Looks OK for me.

**Comment by chiarazampolli** [comment]
+1

**Comment by mpuccio** [comment]
There is a compilation error:
```/System/Volumes/Data/build/ci_checks/alice_ci_0/aliroot/sw/SOURCES/AliRoot/1396/0/STEER/STEER/AliMC.cxx:1199:41: error: implicit conversion from 'long' to 'Int_t' (aka 'int') changes value from 6600000020 to -1989934572 [-Werror,-Wconstant-conversion]```
the PDG code you chose is too large to be casted to int. You might use the convention that we used for the d* (same coding of nuclei but with leading 9 instead of 10).

**Comment by alcaliva** [comment]
Hi @mpuccio , thank you for your suggestion. I give it a try.
Alberto

**Comment by chiarazampolli** [comment]
+1

**Pull request merged**
