### PR TITLE
one more memory leak in AliADQAchecker fixed

### PR DESCRIPTION
**Pull request by hcab14**
- memory leak in GetQABox fixed
- removed unneeded SetRangeUser helper function
- replaced DrawClone -> Draw whenever applicable

For some reason, other commits show up in this PR, I hope this is not a problem.

### CODE REVIEW

**Comment by mbroz84** [comment]
+1

**Comment by Barthelemy** [comment]
We would need a new tag for P2 after the approval of this PR.

**Comment by shahor02** [comment]
+1

**Comment by ktf** [comment]
Please follow up in JIRA about the new release.

**Comment by dberzano** [comment]
Yes for the record it's being followed up in [ALIROOT-7258](https://alice.its.cern.ch/jira/browse/ALIROOT-7258) with the relevant persons as watchers already.

**Pull request merged**
