### PR TITLE
Adding special treatment of monopoles in TPC hit creation

### PR DESCRIPTION
**Pull request by miweberSMI**

### CODE REVIEW

**Comment by miweberSMI** [comment]
Dear @miranov25, all,

here is the change in TPC hit creation for monopoles we discussed in mails. Soem further optimization is needed of course. Please let me know what you think.

Thanks and cheers,
Michael

**Comment by miranov25** [comment]
Hallo Michael.

* 1.) I assume that the change is "back compatible". Checking diff, It should affect only  magnetic monopole.
* 2.) For the speed consideration (in separate e-mail) we can gain speed in case we will use non linear grouping of the Nel for Nel > 300 
* 3.) As we discussed in e-mail exchange next step is to implement saturation in the digitizer.

We can decouple point 2 and point 3 for the next pull request, but I would like to ask you to run the test to proof that the change is back compatible (no difference in case of non monopoles)

Marian

**Comment by miranov25** [comment]
Hallo Michael
I checked that the yout TPC files are bite-wise the same:
{code}
aliensh:[alice] [6] /alice/cern.ch/user/m/miranov/ >ls -l /alice/cern.ch/user/m/miweber/monopoleTests/pionTest_aliroot_modified/TPC*root
-rwxr-xr-x   miweber  miweber        726673 Oct 02 18:04    TPC.Digits.root                                 
-rwxr-xr-x   miweber  miweber         14548 Oct 02 18:04    TPC.Hits.root                                 
aliensh:[alice] [7] /alice/cern.ch/user/m/miranov/ >ls -l /alice/cern.ch/user/m/miweber/monopoleTests/pionTest_aliroot_master_standardConfig/TPC*
-rwxr-xr-x   miweber  miweber        726673 Oct 02 18:29    TPC.Digits.root                                 
-rwxr-xr-x   miweber  miweber         14548 Oct 02 18:29    TPC.Hits.root                                 
{code}
I'm approving step 1.

Marian

**Comment by miranov25** [comment]
+1

**Comment by miweberSMI** [comment]
Hi @miranov25,

thanks a lot. Do we need also a porting request to have it in the next AliRoot tag?

Thanks and cheers,
Michael

**Pull request merged**
