### PR TITLE
Port fixes  of Ivana preventing crashes with Geant4 to V5 09 54 patches

### PR DESCRIPTION
**Pull request by gconesab**

### CODE REVIEW

**Comment by gconesab** [comment]
Hi @pzhristov or @TimoWilken , can you approve?

**Comment by TimoWilken** [comment]
Hi @gconesab, just to confirm, should *all* the commits in this PR be cherry-picked? There are more than just Ivana's fix. If you confirm, I'll merge.

**Comment by gconesab** [comment]
Hi @TimoWilken, yes please, we had ported in between tags some non essential commits that were introduced to master that can be potentially needed. If I remember well most of the commits are needed because of the commit "PDG masses 20 years fix"

Cheers ... Gustavo

**Comment by TimoWilken** [comment]
Merged both PRs, thanks @gconesab! Will you need new v5-09-54 and v5-09-56 tags right away or should I wait?

**Comment by gconesab** [comment]
Hi @TimoWilken, yes please tag them, at least v5-09-56, I will open a jira ticket

**Pull request merged**
