### PR TITLE
fix the bug in AliDataFile.h to add the OADB path twice

### PR DESCRIPTION
**Pull request by mazimm**
call Open method from TFile and not from AliDataFile which would add the OADB path again.

### CODE REVIEW

**Comment by jgrosseo** [comment]
+1

**Comment by dberzano** [comment]
+test

@qgp can you have a look please?

**Comment by qgp** [comment]
Hi @dberzano,

just had a look with Markus, looks fine to me. As soon as tests pass, can we get the tag to go ahead with testing on the LEGO trains?

Cheers,
   Jochen

**Comment by dberzano** [comment]
OK, can you take care of porting the changes to the "CERN Git" AliRoot if tests are green? :-)

**Comment by qgp** [comment]
yep, will do

**Comment by dberzano** [comment]
+1

**Comment by dberzano** [comment]
Today's `_GITHUB` tag will have this change.

**Comment by jgrosseo** [comment]
Hi Dario,
We had a brief discussion with Peter, and the best to tag both now, such that we can save some time.
Thanks!

**Comment by dberzano** [comment]
Alright @jgrosseo, @pzhristov, `_GITHUB` daily is being built already. You'll receive the usual notification email. Note @mazimm that for test trains, as usual, you won't need to wait 2h for the CVMFS propagation, as the tag will be immediately available.

**Comment by dberzano** [comment]
Ready to be used for trains (on local tests) now. @mazimm, @jgrosseo can you give it a try?

**Pull request merged**
