### PR TITLE
EMCAL raw data fitter

### PR DESCRIPTION
**Pull request by mpoghos**
faster raw data fitter

### CODE REVIEW

**Comment by gconesab** [comment]
+test

**Comment by shahor02** [comment]
+test

**Comment by mfasDa** [comment]
+1 

@shahor02 This is a new fast version of the EMCAL raw fitter, intended for O2, which we would like to test first on run2 data. Could you please approve the PR once the tests pass?

**Comment by shahor02** [comment]
+1

**Pull request merged**
