### PR TITLE
fix comment on shower shape data members

### PR DESCRIPTION
**Pull request by gconesab**

### CODE REVIEW

**Comment by gconesab** [comment]
Dear aliroot powers,
can any of you approve this simple change in a couple of comments? This is just to avoid some confusions.
Regards ... Gustavo

**Comment by chiarazampolli** [comment]
+1

**Comment by chiarazampolli** [comment]
Sure, done! Sorry for overlooking.

Chiara

**Comment by gconesab** [comment]
thanks @chiarazampolli, no problem, it is normal to overlook.

Gustavo

**Pull request merged**
