### PR TITLE
Fix compilation gcc10

### PR DESCRIPTION
**Pull request by wiechula**

### CODE REVIEW

**Comment by wiechula** [comment]
I have to admit I'm not sure about the fix in the fortran code. Perhaps an expert can comment if this is ok.

**Comment by chiarazampolli** [comment]
The change looks harmless to me, if @pzhristov wants to have a further look... For now I give a "+test"

**Comment by chiarazampolli** [comment]
+ test

**Comment by chiarazampolli** [comment]
+test

**Comment by ktf** [comment]
+1

**Comment by chiarazampolli** [comment]
Merged by hand because macos does not work now.

**Pull request merged**
