### PR TITLE
Include additional hidden strangeness Pentaquark states

### PR DESCRIPTION
**Pull request by JakeMartinez**

### CODE REVIEW

**Comment by gconesab** [comment]
Hi  @amorsch, is this commit ok and the final solution?

**Comment by amorsch** [comment]
It was ok for my own tests. I think we can go ahead.

**Comment by chiarazampolli** [comment]
+1
Following Andreas' feedback, I am approving.

**Comment by gconesab** [comment]
Hi @ktf,
this commit was approved 5 days ago but it has still not merged. Is the system stuck somehow?
Thanks ... Gustavo

**Pull request merged**
