### PR TITLE
Disable JSON when ROOT HTTP is not available

### PR DESCRIPTION
**Pull request by dberzano**

### CODE REVIEW

**Comment by dberzano** [comment]
+test (do not merge yet!)

**Comment by dberzano** [comment]
@pzhristov @miranov25 I had to disable the only class using JSON from ROOT's HTTP when the latter is not available.

Note that by default JSON will *always* be available, except when building DAs, where we do not need it. The measure was necessary as DAs are built statically, and libRHTTP from ROOT does not play well if statically included - plus it considerably increases the DA size for an unneeded feature.

Just bear in mind to use the same "disabling" techniques I have used in case further classes requiring JSON are added in the future :-)

**Comment by dberzano** [comment]
Please hold on and do not approve yet.

**Comment by dberzano** [comment]
+1

**Comment by pzhristov** [comment]
Hi Dario,
Thank you very much, I forgot that the DA are using static library and did not test this case.

Cheers,
Peter

**Pull request merged**
