### PR TITLE
[EMCAL-33] Added EMCAL clusterizer to HLT

### PR DESCRIPTION
**Pull request by rhaake**
Implementation of EMCAL clusterizer on HLT.

### CODE REVIEW

**Comment by davidrohr** [comment]
+test
Kind Regards
David Rohr

(Sent from my mobile, excuse the typos.)

**Comment by mkrzewic** [comment]
+test

**Comment by rhaake** [comment]
Hi,
  any idea, what's going wrong here? I cannot access the logs. Locally, it worked (tested on ROOT5).
Thanks & best,
Ruediger

**Comment by davidrohr** [comment]
this can be a problem of the ci. i can check later,but anyway, i can deploy it on the farm without merging it to master.
Kind Regards
David Rohr

(Sent from my mobile, excuse the typos.)

**Comment by rhaake** [comment]
Thanks, understood!
Best,
Ruediger

**Comment by mkrzewic** [comment]
+1

**Pull request merged**
