### PR TITLE
Merge recent developments for HLT/O2 tracking + related changes and fixes

### PR DESCRIPTION
**Pull request by davidrohr**

### CODE REVIEW

**Comment by shahor02** [comment]
@davidrohr : as far as I can see, this affects only HLT proper code, the QA and calibration are not affected, could you confirm?
Cheers,
 Ruben

**Comment by shahor02** [comment]
+test

**Comment by davidrohr** [comment]
@shahor02 : I'll have a small PR in AliPhysics for some changes in the QA. This here affects only HLT, + minor fixes in shuttle to compile with GCC7 and to AliReconstruction for the HLT ESD.

**Comment by shahor02** [comment]
+test

**Comment by chiarazampolli** [comment]
+1

**Pull request merged**
