### PR TITLE
fix issue for the direct gamma generation in triggered pythia

### PR DESCRIPTION
**Pull request by iarsene**

### CODE REVIEW

**Comment by gconesab** [comment]
Hi Ionut, I do not see why this is needed. fPhotonInCalo is not used, I guess I left it for backward compatibility.

**Comment by iarsene** [comment]
Hi Gustavo, we use it now in AliGenPythiaFOCAL, which is in the FOCAL package. This seems to cure a problem we were having in generating direct isolated gamma.

**Comment by chiarazampolli** [comment]
+1

**Comment by TimoWilken** [comment]
Errors unrelated; merged.

**Pull request merged**
