### PR TITLE
Sync AliGPU (O2 commit e4c882f7dead6c718f078148cf55662e3faeb102)

### PR DESCRIPTION
**Pull request by davidrohr**

### CODE REVIEW

**Comment by davidrohr** [comment]
+test

**Comment by davidrohr** [comment]
@ktf @chiarazampolli : Is this a real problem with the el6native builder?

**Comment by chiarazampolli** [comment]
Ciao @davidrohr ,
I cannot find the issue in the log. Have you?

**Comment by davidrohr** [comment]
No, it fails already at aliDocter level so there is no log

**Comment by TimoWilken** [comment]
@davidrohr @chiarazampolli @ktf Here's the full error message for `build/AliRoot/el6native`:

```
++ timeout -s9 600 aliDoctor --defaults el6native AliRoot
usage: aliBuild [-h] [-d] [-n]
                {analytics,architecture,build,clean,deps,doctor,init,version}
                ...
aliBuild: error: Default `el6native' does not exists. Viable options:
- coverage
- o2-dataflow
- o2-dev-fairroot
- prod-latest
- release
- o2
- generators
- user-next-root6
- jalien
- user
- next-root6
```

Perhaps this is an old test, should it be removed?

**Comment by ktf** [comment]
yes, I just did it.

**Pull request merged**
