### PR TITLE
V5 09 57 patches

### PR DESCRIPTION
**Pull request by chiarazampolli**

### CODE REVIEW

**Comment by chiarazampolli** [comment]
Hello @TimoWilken , 

I don't know why I had the previous commits, which I had already ported the other time. But to my understanding, all is fine. What do you think? I would let you take care of the merging, after you check that I did not mess things up.

Thanks!

Chiara

**Comment by chiarazampolli** [comment]
I checked also the files changed, and only the modifications of the commits that I cherry-picked are there:
https://github.com/alisw/AliRoot/pull/1318/commits/64ebd8a507b9db0d2ae8b10ea72d6eaa9dc0172d
https://github.com/alisw/AliRoot/pull/1318/commits/28388aebc5a57bec0346b999938d35bc6b315159

So everything should be fine.

**Comment by TimoWilken** [comment]
Hi @chiarazampolli, I've cherry-picked the two commits directly onto [v5-09-57-patches](https://github.com/alisw/AliRoot/commits/v5-09-57-patches), so we don't have duplicate commits.

**Comment by chiarazampolli** [comment]
Hi @TimoWilken , 

Thanks! Can you tell me what happened in my cherry-pick? The net result would have been fine, as I said. I had rebased to the branch before the cherry-picking, wasn't this the correct way?

Chiara

**Comment by TimoWilken** [comment]
Hi Chiara, I suppose it would've been fine, but I wanted to make extra sure. :) It looks like you have different commits on your local branch than on the remote, so you merged the remote branch into yours, giving the duplicate history. (Maybe git auto-merged this for you when you did a `git pull`.)

`git diff origin/v5-09-57-patches chiarazampolli/v5-09-57-patches` shows no differences for me, so you could do something like:
```bash
$ cd AliRoot
$ git fetch https://github.com/alisw/AliRoot v5-09-57-patches
$ git diff v5-09-57-patches FETCH_HEAD
$ # if there is no output, then:
$ git checkout -B v5-09-57-patches FETCH_HEAD
$ git push -fu origin v5-09-57-patches  # assuming your own fork is the 'origin' remote
```
...if you want to have exactly the same branch locally as in alisw/AliRoot.

**Comment by chiarazampolli** [comment]
Ciao @TimoWilken ,
You did perfectly fine!! I myself wanted that you checked :-) 
I will try what you suggested here for the next time. It was weird since I had opened the PR from my branch in my repo, so I supposed things were fine.
Cheers,
Chiara

**Pull request closed without merging**
