### PR TITLE
ATO-418: AliParser (NEW class),  AliDrawStyle, AliPainter 

### PR DESCRIPTION
**Pull request by miranov25**
###    AliParser  + AliParserTest.C (Boris)
* New class with static function for the the string parsing 
  * used in AliDrawStyle and AliPainter
  * plan to use AliParser functionality  for option parsing in the AliTMinuitToolkit and TStatTookit ()
*  Added new functions examples:
  * Slice;
   * Slice2Matrix;
* Doxygen documentation wrote;
* Tests added to ctest
###    AliPainter:
*   Part of implementation rewritten using  new functions from AliParser;
*   Bug with numbers in limits was fixed;
*    Global maps and variables were change to local;
###    AliDrawStyle:
* Part of implementation rewritten using  new functions from AliParser;
* Bug fixes and optimizations;

Code was installed without error. All tests passed.

### CODE REVIEW

**Comment by miranov25** [comment]
+test

**Comment by miranov25** [comment]
Dear all.
Could I ask somebody to review changes? 
Marian

**Comment by shahor02** [comment]
+1

**Comment by miranov25** [comment]
Hallo @bdrum 

The code failed in the AliParser.cxx. Checking the error message and the code, I see you used the std::find  which was introduced recently. Could you check that the code compile also with historical C++98 compiler used in AliRoot.
In case you can  not do modification now  I will try to make patch on Friday.

For others, how we can check that the code will compile in the tests? Of course for our Ubuntu compilation all tests went fine. 

Marian.

**Comment by miranov25** [comment]
Hallo @bdrum and @shahor02.

I commented out the part of the code which failed. @bdrum  please modify affected part (std::find) using C++98 standards.
@shahor02, could you please trigger the test. I hope this was the only part which use "new" C++.

Marian

**Comment by shahor02** [comment]
+1

**Comment by miranov25** [comment]
+1

**Pull request merged**
