### PR TITLE
Geometry updates for AD detector

### PR DESCRIPTION
**Pull request by ecalvovi**
This updates geometry of several structures surrounding ADA and ADC detector. Most importantly the dipole compensator magnet on A-Side.

### CODE REVIEW

**Comment by sawenzel** [comment]
There are 3 commits with the same name "Update geometry (part I)". I think we should try to avoid duplications like this and provide the changes in a single relevant commit.

**Comment by ecalvovi** [comment]
You are right @sawenzel. I didn't because I had a problem with the command line so I used the web interface file by file for those first three commits. My bad.

**Comment by mbroz84** [comment]
+1

**Comment by dberzano** [comment]
@ecalvovi can you please squash the relevant commits as discussed with @sawenzel?

**Comment by mbroz84** [comment]
+1

**Comment by chiarazampolli** [comment]
Hello,

Does this commit affect data processing or simulation?

Cheers,

Chiara

**Comment by dberzano** [comment]
Hi, can you please, as asked twice already by me and @sawenzel, squash the commits?

**Comment by sawenzel** [comment]
Something strange is going on here. Another commit was added but the original un-squashed commits are still there. I also notice 3 merge commits. Why is this necessary?

The usual suggested workflow is the following:

   a. `git pull origin master` // bring your master up to date with origin
   b. `do some work` 
   c. `git commit your work`
   d. `git push yourfork master`
   e. ask for pull request

In order to modify commits already done, consider to use the `git rebase -i` command which let's you modify/squash/delete/reorder commits. Once done, you need to push to your branch using a forced push `git push -f`

**Comment by ecalvovi** [comment]
I'm afraid that by trying to squash I'm doing things worse. Sorry but I'm not an expert on git.

**Comment by sawenzel** [comment]
I can offer to cleanup this PR in order advance here. Will let you know when it's done.

**Comment by ecalvovi** [comment]
Yes please, that will help a lot. Thanks @sawenzel

**Comment by ecalvovi** [comment]
Hi @chiarazampolli, this affects AD simulation. No data processing. Cheers.

**Comment by sawenzel** [comment]
I cleaned up this commit using the following procedure:
a. `git diff -p master...  > patch` # find out everything that changed w.r.t master and make patch
b. `git checkout master; git apply patch` # apply patch to original master
c. `git commit -m "New commit"` # make a fresh commit

A will make a new PR. We should close this one.

@dberzano : As an approver, I would like to be able to say "+1 :squash:" and alibot could do this cleanup work automatically.

**Comment by dberzano** [comment]
@sawenzel we have decided after long discussions not to introduce the ability to merge-squash pull requests after considering the chances of losing work by the average developer :-(

**Comment by ecalvovi** [comment]
Thanks a lot @sawenzel. Then I guess I should close this request.

**Comment by sawenzel** [comment]
@dberzano : Then I can give my user story a slightly different twist: 

As a developer without large git experience, I would like to be able to say 'Hey Alibot: Please go ahead and squash my PR and work into a nice clean commit!'

**Pull request closed without merging**
