### PR TITLE
Add Theta_c pentaquark

### PR DESCRIPTION
**Pull request by fgrosa**

### CODE REVIEW

**Comment by gconesab** [comment]
Hi @ktf,
clicking on the full log link I see that the build succeeded but for some reason it does not want to validate it. Any idea how to make this commit be merged?
Thanks ... Gustavo

**Comment by ktf** [comment]
@MichaelLettrich @TimoWilken could you check what is going on with the AliRoot tests? They seem to be stuck.

**Comment by gconesab** [comment]
Can anyone of the approvers give +1?

**Comment by chiarazampolli** [comment]
+1

**Pull request merged**
