### PR TITLE
Update Xi_c ctau

### PR DESCRIPTION
**Pull request by gconesab**

### CODE REVIEW

**Comment by gconesab** [comment]
Hi all, can anyone approve?
Thanks ... Gustavo

**Comment by gconesab** [comment]
Ciao @chiarazampolli, can you approve here or you have the same message about conflicts?

**Comment by gconesab** [comment]
Hi @TimoWilken, if you do not have conflicts, can you merge?

**Comment by chiarazampolli** [comment]
Hello @TimoWilken , 
I saw again conflicts on this PR and on PR 1477... No idea why. Maybe when you are back we can check together?

**Pull request merged**
