### PR TITLE
add AliGenEvtGen header to preserve index generator assignment

### PR DESCRIPTION
**Pull request by miweberSMI**

### CODE REVIEW

**Comment by miweberSMI** [comment]
Hello @chiarazampolli , @fprino , @ktf , all,

this is the back-port we need to run the DQ production with the fix by @ffionda and @shahor02 (hope it went OK, since I didnt do this for some time now).

Thanks and cheers,
Michael

**Comment by shahor02** [comment]
@miweberSMI : you may also need to backport my new fix https://github.com/alisw/AliRoot/pull/1067,
see the message I've just sent as reply to @ffionda

**Comment by miweberSMI** [comment]
Hi @shahor02,
thanks for checking again (I did not have time to test it today)! I added also #1067 ...
Cheers,
Michael

**Comment by chiarazampolli** [comment]
Ciao @miweberSMI , 

Can you also open a JIRA porting request? 
@ktf , this is the PR we discussed.

Cheers,

Chiara

**Comment by miweberSMI** [comment]
Done: https://alice.its.cern.ch/jira/browse/ALIROOT-8369

**Pull request merged**
