### PR TITLE
 split AliEMCALRecoUtils into AliEMCALRecoUtils and AliEMCALRecoUtilsBase

### PR DESCRIPTION
**Pull request by gconesab**
First step before moving AliEMCALRecoUtils to AliPhysics

### CODE REVIEW

**Comment by gconesab** [comment]
+test

do not approve yet, please review

**Comment by chiarazampolli** [comment]
Ciao Gustavo,

Do I understand correctly that I should not approve? I reviewed the change in AliAnalysisTaskESDfilter.cxx, there it is simple, and ok, the rest is in EMCAL. If I approve for the filtering task, though, I am afraid that everything will be approved.

Cheers,
Chiara

**Comment by gconesab** [comment]
Ciao Chiara,

Yes, let's just approve the testing and on Monday if there are no comments from Emcal we can approve.
Thanks  .... Gustavo

**Comment by chiarazampolli** [comment]
+test

**Comment by shahor02** [comment]
Hi,
To me it looks ok, though since the AliEMCALRecoUtils derives from the AliEMCALRecoUtilsBase, I don't see why do you need to explicitly alias ExtrapolateTrack... methods of AliEMCALRecoUtils to AliEMCALRecoUtilsBase and add extra 3 commits changing AliEMCALRecoUtils methods to AliEMCALRecoUtilsBase.
Cheers,
 Ruben

**Comment by gconesab** [comment]
Hi Ruben,

the idea is to move this AliEMCALRecoUtils class to AliPhysics, thus the need of aliases. The reason for such move is that since this class is heavily used in Analysis a simple bug fix needs a new aliroot tag, which takes some time and it  is not completely necessary. I will profit the next tag to remove this class from aliroot and put it on AliPhysics.

Since we received not more comments, can be this approved? Thanks

**Comment by shahor02** [comment]
Hi Gustavo,
If AliEMCALRecoUtils inherits from AliEMCALRecoUtilsBase, it inherits also all its methods, it does not matter if you leave it in the aliroot or move to aliphysics. So the aliases are redundant. Anyway, they will not hurt, I'll approve the PR
Cheers,
 Ruben

**Comment by shahor02** [comment]
+1

**Pull request merged**
