### PR TITLE
[WIP] Utilize new features of AliTPCCommon (fast transform, HLT tracks in offline, ...)

### PR DESCRIPTION
**Pull request by davidrohr**
This requires AliTPCCommon >= v1.4

@dberzano : This will require people to update their alidist. Merging is not urgent. Could you please pull it in whenever it seems suited for you.

@shahor02: The changes to AliTPCTracker are completely inactive if you do not set AliTPCReconstructor::SetUseHLTTracks(), so it will not affect normal reconstruction, but if you want you can have a look and double-check.

### CODE REVIEW

**Comment by davidrohr** [comment]
+test

**Comment by davidrohr** [comment]
+test

**Comment by dberzano** [comment]
Yes, see my comment on alisw/alidist#1315. See also [ALIROOT-8007](https://alice.its.cern.ch/jira/browse/ALIROOT-8007).

**Comment by davidrohr** [comment]
+test

**Comment by dberzano** [comment]
+1

**Pull request merged**
