### PR TITLE
sprintf to snprintf

### PR DESCRIPTION
**Pull request by mhemmer-cern**
- sprintf is deprecated and should be changed with snprintf. This is done for all of AliRoot with this PR
- Notable things:
    - in `./ITS/ShowSPDRecPoints.C` there were cases where the lenth of the const char objects was too small for the messages that are streamed into them. I increased the length to ensure memory safety.
    - in `AD/ADrec/AliADQADataMakerRec.cxx` it was `if(mulADC!=0)FillRawsData(kChargeADC_PC,chargeTrigADA/mulADC)` which I changed to `if(mulADC!=0)FillRawsData(kChargeADC_PC,chargeTrigADC/mulADC);` since it seemed correct to divide ADC by ADC and not ADA by ADC
- Removal of unsused variables

### CODE REVIEW

**Comment by mhemmer-cern** [comment]
Hello @ktf, @pzhristov and @davidrohr 

When trying to build AliRoot in debug mode on Mac I got a lot of error messages due to our change to C++20. This PR includes all changes made to remove these error messages, which are mainly switching from `sprintf ` to `snprintf`. Also there are minor changes to potential problems that I saw when trying to remove all the error messages (see the PR description).

I know this is a very big PR especially for AliRoot in 2024. Please let me know how we should handle this PR in your opinion.

**Comment by davidrohr** [comment]
+test

**Comment by mhemmer-cern** [comment]
Thank you @davidrohr :)

**Comment by mhemmer-cern** [comment]
I forgot to revert the build type in the CMakeList.txt before making the PR. The latest commit changes that back. 
Sorry for that oversight.

**Comment by davidrohr** [comment]
+test

**Comment by mhemmer-cern** [comment]
The test was okay, can you approve this now, or is there something else that needs to be done @davidrohr ?

**Comment by davidrohr** [comment]
+test

**Pull request merged**
