### PR TITLE
Adapt macros to doxygen, second part

### PR DESCRIPTION
**Pull request by gconesab**

### CODE REVIEW

**Comment by gconesab** [comment]
Why can't I approve this request? Too many changes?

**Comment by ktf** [comment]
+test
yes, we have a safety limit to 50 files modified, IIRC. Above that one of the "usual suspects" needs to approve. In general I suggest not to mix different developments in one PR. Here you have something which is merely doxygen cleanups, some reformatting, and some actual code changes, is that intended?

**Comment by gconesab** [comment]
This commit is intended as is. I planned just to do some few doxygen changes but then I also decided to move some macros of place.

**Comment by gconesab** [comment]
A kind reminder/request to approve. Thanks

**Comment by pzhristov** [comment]
+1

**Pull request merged**
