### PR TITLE
Preparatory fixes for next AliTPCCommon tag

### PR DESCRIPTION
**Pull request by davidrohr**

### CODE REVIEW

**Comment by dberzano** [comment]
+test (I believe this will have to be merged _after_ bumping AliTPCCommon, can you confirm @davidrohr?)

**Comment by davidrohr** [comment]
@dberzano : No, this should be merged BEFORE.
Same for AliceO2 repo.

There'll be another PR afterwards to use TRD tracking and TPC space charge distortions stuff from AliTPCCommon.

**Comment by dberzano** [comment]
Thanks for clarifying then!

**Comment by dberzano** [comment]
+1

**Pull request merged**
