### PR TITLE
update RecoParam for 2017

### PR DESCRIPTION
**Pull request by pillot**

### CODE REVIEW

**Comment by aphecetche** [comment]
+test

**Comment by aphecetche** [comment]
+1

**Comment by chiarazampolli** [comment]
Ciao Philippe,

To be sure: when I did the upload of the object today I didn't use a fresh master. Did you check its content?

Regards,

Chiara

**Comment by pillot** [comment]
Ciao Chiara,

Yes I did (and just checked again ;-)) and it is fine. Just for my understanding, could the upload of an already produced object actually change it's content?

Cheers,
Philippe

**Comment by chiarazampolli** [comment]
Ciao Philippe,
Thanks for checking! As the streamer is involved, I would say so yes :) 
Cheers,
Chiara

**Comment by pillot** [comment]
Ok, good to know! Thanks for the clarification :-)
Cheers,
Philippe

**Pull request merged**
