### PR TITLE
Sync AliGPU

### PR DESCRIPTION
**Pull request by davidrohr**

### CODE REVIEW

**Comment by davidrohr** [comment]
+test

**Comment by davidrohr** [comment]
@sgorbuno : Your new splines interface fails compilation in AliRoot. Could you have a look?

**Comment by sgorbuno** [comment]
> @sgorbuno : Your new splines interface fails compilation in AliRoot. Could you have a look?

@davidrohr, I can't compile AliRoot with alidock, it fails at python-modules. 
I'll try it without alidock.

**Comment by sgorbuno** [comment]
@davidrohr, 
I can compile AliRoot after this fix: https://github.com/AliceO2Group/AliceO2/pull/4841

**Comment by davidrohr** [comment]
+test

**Comment by davidrohr** [comment]
@sgorbuno: I have pulled in your patch here, let's see if the AliRoot CI passes now, then we can merge it in O2.

**Comment by davidrohr** [comment]
@TimoWilken : I am getting an error building AliRoot but no build log. Could you please check? :(

**Comment by TimoWilken** [comment]
@davidrohr It'll be trouble with GitLab authentication, [the same error as for other PRs](https://cern.service-now.com/service-portal?id=ticket&table=incident&sys_id=7ef72d09dbe0ec106445144e16961995&view=sp). It only sometimes fails, so I'm hoping it'll succeed on a subsequent rebuild. Sorry about that!

**Comment by ktf** [comment]
Issue raised with CERN/IT, actually.

**Comment by davidrohr** [comment]
+test

**Comment by davidrohr** [comment]
+test

**Comment by davidrohr** [comment]
+test

**Comment by davidrohr** [comment]
@sgorbuno : Thx, your patch seems to have worked. I had to fix one more issue, now let's see. Just need to wait until the CI manages to start processing...

**Comment by davidrohr** [comment]
+test

**Comment by davidrohr** [comment]
+test

**Comment by davidrohr** [comment]
@MichaelLettrich : The macos CI has not reported since ~24 hours, could you check?

**Comment by MichaelLettrich** [comment]
on it.

**Comment by MichaelLettrich** [comment]
@davidrohr the macOS CI died, I restarted it.

**Comment by davidrohr** [comment]
Is there perhaps the possibility to add some kind of watchdog such that we get notified when it dies? Perhaps we can work a vit towards minimizing human intervention.

**Comment by davidrohr** [comment]
+1

**Pull request merged**
