### PR TITLE
Bugfix for truncated mean

### PR DESCRIPTION
**Pull request by tdietel**
Fix for issue ALIROOT-7073

### CODE REVIEW

**Comment by AllaMaevskaya** [comment]
+1

**Comment by dberzano** [comment]
Hi @tdietel, could you please rebase your branch with the latest changes from AliRoot?

    git pull --rebase origin master

We cannot approve it as it is.

**Comment by tdietel** [comment]
It seems I had some confusion of the commits in my branch. I cleaned it up and had to force-push to GitHub. I hope it is working now, otherwise I might need some help how to do this.

**Comment by mfasDa** [comment]
@tdietel @dberzano Something seems to be screwed up with the permissions of the TRD directories - please check!

**Comment by tdietel** [comment]
Are the permissions something I can check? I have no idea where to check these permissions.

Should I have permissions to push to the TRD directories?

Could it be related to the force push I had to do?

**Comment by mfasDa** [comment]
This is steered via e-groups. I suspect that this is the e-group git-librarians, but @dberzano might know. For EMCAL we have two e-groups mapped to the ALICE builder, one for AliRoot and one for AliPhysics, and maybe you should consider something similar for TRD. With this we can manage our approvers by ourselves as the two e-groups are managed by us directly.

At least someone from TRD should have approval rights for the TRD directories (but can of course be many, i.e. this case for EMCAL) - currently it looks like it is only me who has approval rights (for reasons not completely clear to me). I am on this list probably only for historical reasons as I had commit rights in svn and they were ported as it is to git.

The force-push is independent of this as you push to your fork. The force push you had to because you did a rebase which changed the history of the branch.

**Comment by tdietel** [comment]
Hello Dario,

could you help us with this and allow me to commit to the TRD directories in AliRoot? Or point me to who can do that for us?

Note, I also made a minor change to the pull request.

Cheers,
 - Tom.

**Comment by dberzano** [comment]
So, the permission check is just fine. The problem was that the original PR contained unrelated changes too, and it needed to be rebased (but I believe this was clarified already).

Current TRD permissions are not associated to any egroup, and this is one of the few places left where this happens.

TRD experts should create an egroup (call it `alice-git-trd` for instance), add the persons they want, and tell us when done. We cannot create or manage detector-specific or PWG-specific egroups.

**Comment by tdietel** [comment]
Hello Dario,

Thanks for the clarification. I have created the group alice-git-trd (as you suggested), so far with me as the only member. Can you set things up. We will then maintain the e-group in TRD.

Cheers,
- Tom.

**Comment by dberzano** [comment]
I have updated the configuration, now TRD is associated to `alice-git-trd`. Thanks!

**Comment by tdietel** [comment]
+1

**Comment by dberzano** [comment]
+1

Hi @tdietel, this is not how it works. As soon as an update is performed to this PR, then the system is triggered again, this time with the new permissions. Permission changes do not affect open and unmodified PRs, and you cannot `+1` if you weren't explicitly mentioned by the PR checker. I am approving it this time (your intentions were clear)!

**Comment by tdietel** [comment]
Hi Dario, 

Thanks for another clarification and approving the commit.

Cheers, Tom.

**Comment by chiarazampolli** [comment]
Ciao Tom,

When the PR will be completed and merged, can you open a JIRA porting request?

Thanks,

Chiara

**Comment by chiarazampolli** [comment]
Porting request: https://alice.its.cern.ch/jira/browse/ALIROOT-7684

Chiara

**Pull request merged**
