### PR TITLE
Adding option to force Lambda_c into Lambda Pi+ Pi0

### PR DESCRIPTION
**Pull request by mfasDa**
Using this channel in all Pi0-based configurations
for the Lambda_c decays.

### CODE REVIEW

**Comment by mfasDa** [comment]
For dedicated charm to pi0 + X productions forcing Lambda_c to go to Lambda pi+ pi0 (largest branching ratio of Lambda_c to pi0 + X). This is handled with an additional option for parameter forcing the Lambda_c decay. For the existing the old behaviour is kept.

**Comment by chiarazampolli** [comment]
Maybe @amorsch could have a look? 

Chiara

**Comment by mfasDa** [comment]
In addition the PR should maybe be approved by the HF experts as the commit affects the decay channels relevant for HF (D2H). Adding @arossi81.

Cheers 

Markus

**Comment by arossi81** [comment]
Hi @mfasDa ,
it looks ok to me.
Cheers,
Andrea

**Comment by chiarazampolli** [comment]
Ok, approving now.
+1

**Comment by dberzano** [comment]
+1 <-- must be the first thing in the PR comment @chiarazampolli

**Comment by chiarazampolli** [comment]
Ah good to know :)

**Pull request merged**
