### PR TITLE
Patch for floating point exception in Ropewalk.cc (by C.Bierlich)

### PR DESCRIPTION
**Pull request by gconesab**
See discussion in JIRA
https://alice.its.cern.ch/jira/browse/ALIROOT-8488
needed for
https://alice.its.cern.ch/jira/browse/ALIROOT-8533

### CODE REVIEW

**Comment by gconesab** [comment]
Please @pzhristov or anyone, approve and I will make a port to v5-09-56-patches

**Comment by sawenzel** [comment]
+test

**Comment by sawenzel** [comment]
+test

**Comment by chiarazampolli** [comment]
+1

**Pull request merged**
