### PR TITLE
Results-based strange particle pt shapes for pp5 to be used in GenParam

### PR DESCRIPTION
**Pull request by bianchil**

### CODE REVIEW

**Comment by bianchil** [comment]
Dear all,
as the commit is necessary for a MC request that we are eager to have, I was wondering if there is anything problematic with this or if I can bug you for a +1 so that we can proceed. Thank you very much in advance!
Putting @alcaliva in cc for info

**Comment by chiarazampolli** [comment]
+1

**Comment by chiarazampolli** [comment]
I am not an expert of this code, but it seems fine to me. Approving to unblock MC.

**Comment by TimoWilken** [comment]
Hi @chiarazampolli, see alisw/alidist#4356 (now merged). I've restarted the check.

**Pull request merged**
