### PR TITLE
Fast dipole parameterization data

### PR DESCRIPTION
**Pull request by syamasak**
related: https://github.com/alisw/AliRoot/pull/552
This PR contains dipole B-field parameterization data (C++ sources and headers)

### CODE REVIEW

**Comment by shahor02** [comment]
+test

please don't merge yet

**Comment by syamasak** [comment]
```
c++: Internal error: Killed (program cc1plus)
Please submit a full bug report.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
make[2]: *** [STEER/STEERBase/AliMagFastDip5k/CMakeFiles/AliMagFastDip5k-object.dir/AliMagFastDip5k.cxx.o] Error 1
make[1]: *** [STEER/STEERBase/AliMagFastDip5k/CMakeFiles/AliMagFastDip5k-object.dir/all] Error 2
```
What is it..?

**Comment by shahor02** [comment]
Looks like the problem was in building with root6. But the error says "c++: Internal error: Killed (program cc1plus)". Could you push some dummy patch, to trigger another build test? Just to be sure it was not a glitch due to the memory etc.

**Comment by syamasak** [comment]
pushed

**Comment by shahor02** [comment]
+test

**Comment by shahor02** [comment]
.. same story: ````c++: Internal error: Killed (program cc1plus)````. @dberzano , any idea what could be the reason of such a message (if not, then I'll need to build aliroot with root6 locally)...

**Comment by chiarazampolli** [comment]
+test

**Comment by chiarazampolli** [comment]
Hello,

I am confused, I tried the "+test" again, and now it says that the commit is merged? 

Chiara

**Comment by chiarazampolli** [comment]
Hi @shahor02 ,

I think one can revert the commit... Should I do it?

Sorry for the mess...

Chiara

**Comment by shahor02** [comment]
Hi @chiarazampolli ,
indeed, there is some anomaly, probably @dberzano should check why +test has merged the PR.
I 've just reverted it.
Cheers,
 Ruben

**Pull request merged**
