### PR TITLE
Add DRGEN generator.

### PR DESCRIPTION
**Pull request by sevdokim**
The DRGEN is a MC event generator for exclusive central diffraction processes.
JIRA ticket: https://alice.its.cern.ch/jira/browse/ALIROOT-7402

### CODE REVIEW

**Comment by dberzano** [comment]
Hi, we are keeping our generators externally now, please get in touch with @alisw/pwgmm and @qgp (Jochen Klein for the record).

Also, I don't see any licensing information for DRGEN. We might not be able at all to legally add this generator to AliRoot.

**Comment by dberzano** [comment]
Any update on this? Can we close it?

**Comment by sevdokim** [comment]
Dear Dario,

I contacted Jochen Klein to discuss this, can we wait a bit more?

Best regards,
Sergey

**Comment by dberzano** [comment]
Yes sure but the point is: our generators are external now, so this PR should be closed as per @alisw/pwgmm's policy. We can leave it open for a while, but eventually - we'll close it.

**Comment by pzhristov** [comment]
+1

**Pull request merged**
