### PR TITLE
Kinematic cuts for DRgen  

### PR DESCRIPTION
**Pull request by sevdokim**
A possibility to produce central system in specified mass, pt and rapidity ranges is added. These cuts were requested by Evgeny Kryshen.

### CODE REVIEW

**Comment by dberzano** [comment]
@amorsch can you please check?

**Comment by amorsch** [comment]
+1

**Comment by dberzano** [comment]
+1 thanks

**Comment by sevdokim** [comment]
I have a 404 error while trying to access a log file:
https://ali-ci.cern.ch/repo/logs/alisw/AliRoot/495/7aa4107a81783b663c02770a58949416fb572dd2/fullLog.txt
How can I see the log?
Thanks,
Sergey

**Comment by dberzano** [comment]
This is a temporary problem, it will clear out automatically, just wait :-)
-- 
--
Dario Berzano
about.me/dario.berzano

**Pull request merged**
