### PR TITLE
Fix floating point exception in Linux guntest

### PR DESCRIPTION
**Pull request by TimoWilken**
Since moving to `o2` defaults, the Linux CI check has been failing in AliRoot-guntest with a floating point exception. Peter tracked this down to a value `> 1.0` being passed to `asin` and provided this fix.

Written-by: Peter Hristov (@pzhristov)

### CODE REVIEW

**Comment by pzhristov** [comment]
+1

**Comment by pzhristov** [comment]
+1

**Comment by pzhristov** [comment]
+1

**Comment by TimoWilken** [comment]
I've force-pushed to remove the last commit, which deleted `gSystem->Load` calls from testing macros, but this ended up not helping. The code now fixes the original floating-point exception, though further issues remain.

Merging this, pending further work on the other issues.

**Pull request merged**
