### PR TITLE
Updates in ConverterJSON

### PR DESCRIPTION
**Pull request by jmyrcha**
…TTP library

### CODE REVIEW

**Comment by dberzano** [comment]
+test @jmyrcha I assume you have verified this, right?

**Comment by jmyrcha** [comment]
Change was required to build aliceToJson tool. I have tested that after change it was built.

**Comment by dberzano** [comment]
According to this file:

https://github.com/alisw/AliRoot/blob/master/cmake/FindROOT.cmake

you are right, `ROOT_HASHTTP` is the correct variable to use. Will approve when tests are OK.

**Comment by dberzano** [comment]
Hi @jmyrcha, did you push the new commit by mistake? It does not seem in line with the PR title. Please revert it, or change the PR title accordingly.

**Comment by dberzano** [comment]
+1 (and thanks!)

**Pull request merged**
