### PR TITLE
fix L0 time array overflow due to null L0 threshold from OCDB EMCAL-39

### PR DESCRIPTION
**Pull request by guernane**
everything is in the title, should fix the old standing EMCAL-39 ticket.
@mfasDa  should be enough to remove the Fatal (to be turned into an Error?) in the TriggerElectroncis constructor, do you think we should include that in the same PR?

### CODE REVIEW

**Comment by loizides** [comment]
Hi, I would keep the two patches separate. Good for me to go on. Constantin

**Comment by loizides** [comment]
+1

**Comment by mfasDa** [comment]
Hi @guernane, Hi @loizides,

Yes, error is the appropriate. This is the default log level for grid jobs.

It is OK for now to separate into two patches but in general one should be cautious with the fragmentation into trivial patches because it will become tricky to find certain commits in the history.

Cheers

Markus

**Comment by loizides** [comment]
Ah ok, my reasoning was to perhaps cherry pick this patch in the future, in case we need to backport , etc

**Pull request merged**
