### PR TITLE
Created AliGenSexaquarkReaction, needed for  ALIROOT-8862

### PR DESCRIPTION
**Pull request by gconesab**

### CODE REVIEW

**Comment by gconesab** [comment]
Hi @TimoWilken, can you merge this and tag again? Geant3 MC so nothing complicated :)

**Comment by TimoWilken** [comment]
Done and tagged v5-09-54r @gconesab. The tag is now being compiled. This is without the new GEANT4, so just like the older v5-09-54 tags -- I assume that's sufficient for G3-based MC; let me know if not!

**Comment by gconesab** [comment]
Thanks @TimoWilken! It should be ok.

**Comment by TimoWilken** [comment]
Hi @catalinristea, sorry, there was a problem with the AliPhysics build (it could not find CGAL for some reason). The AliRoot build worked. I'm looking into it!

**Comment by catalinristea** [comment]
Hi Timo,

As far as I remember, we'll need also AliPhysics, as it contains many of AOD related parts. I'm confident you'll manage to find a solution to the CGAL version issue. Thanks a lot!

Yours, Catalin.

**Comment by catalinristea** [comment]
Hi Timo! Thanks a lot!
Yours, Catalin.

**Pull request merged**
