### PR TITLE
Adding Xic+->pK-pi+ (including Xic+->pK0*), Xic+->Xi-pi+pi+ (includin…

### PR DESCRIPTION
**Pull request by arossi81**
…g Xic+->Xi*0 pi+), Xic0->Xi-pi+ decays, OmegaC->OmegaPi to ForceHadronicD; adding Bs->Ds- pi+ to ForceBeautyUpgrade; fixes to ForceBeautyUpgrade in AliDecayerPythia8. Adding Xic0 and Bs to AliGenITSULib. Decay table modified to update Xic0, Xic+ and OmegaC decay channels.

### CODE REVIEW

**Comment by arossi81** [comment]
Hi @amorsch , @qgp ,@shahor02,@chiarazampolli,
could you have a look and possibly approve it (or comment)?

Cheers,
Andrea

**Comment by chiarazampolli** [comment]
Ciao,

I can approve only one part of the PR. Maybe @qgp could approve everything directly?

Chiara

**Comment by davidrohr** [comment]
+test

**Comment by davidrohr** [comment]
@chiarazampolli : Shall I merge it?

**Comment by qgp** [comment]
+1
looks good to me

**Comment by qgp** [comment]
+1

**Comment by chiarazampolli** [comment]
Thanks David and Jochen!

Chiara

**Comment by arossi81** [comment]
Thanks!

**Comment by arossi81** [comment]
Hi @davidrohr, @qgp ,
could you +1 it? 

Cheers,
Andrea

**Comment by davidrohr** [comment]
+1

**Comment by arossi81** [comment]
thanks!

**Pull request merged**
