### PR TITLE
Restore option to generate weighted events in AliGenPythiaPlus and ad…

### PR DESCRIPTION
**Pull request by mfasDa**
…d setting for AliPythia8

### CODE REVIEW

**Comment by mfasDa** [comment]
@amorsch Could you please have a quick look if this is OK?

**Comment by ktf** [comment]
+test

not sure why touching pythia means that "usual suspects" are included in the list. Maybe because it's imported in our repo...

**Comment by amorsch** [comment]
Look OK for me.

**Comment by mfasDa** [comment]
@amorsch Thanks a lot for checking?
@ktf Could you then please merge the pull request?

**Comment by davidrohr** [comment]
+1

**Pull request merged**
