### PR TITLE
Set new AliVTrack::kTRDupdate in AliESDtrack::fFlags if TRD was used …

### PR DESCRIPTION
**Pull request by shahor02**
…in update

Note: we already had 32 flags, the enum in the AliVTrack could not accomodate more.
Therefor the kTRDupdate is defined as bit 33.

### CODE REVIEW

**Comment by shahor02** [comment]
+1

**Comment by shahor02** [comment]
+test

**Comment by MarekKowalski1504** [comment]
+1

**Comment by shahor02** [comment]
+1

**Comment by MarekKowalski1504** [comment]
+1

**Pull request merged**
