### PR TITLE
Adding Event header name

### PR DESCRIPTION
**Pull request by miweberSMI**
- needed for T0 digitization task

### CODE REVIEW

**Comment by miweberSMI** [comment]
Hi @sevdokim, all,

I modified the DRgen generator task adding an generator name in the header. This is needed for the T0 digitization task.
I hope this change is OK with you.

Cheers,
Michael

**Comment by dberzano** [comment]
+test

**Comment by miweberSMI** [comment]
Hi @sevdokim, @qgp,

could you have a look at the changes and approve it if you agree.

Cheers,
Michael

**Comment by sevdokim** [comment]
Hi, @miweberSMI ,
it seems to be fine for me.
Cheers,
Sergey

**Comment by miweberSMI** [comment]
Dear all,

by accident I added a small update for the Exodus decayer here. But I hope it can be approved as well on this PR.

Thanks and cheers,
Michael

**Comment by miweberSMI** [comment]
+test

**Comment by amorsch** [comment]
+1

**Comment by dberzano** [comment]
+1

**Pull request merged**
