### PR TITLE
AliFITv8: Remove old containing volumes and some of the screws, rods,…

### PR DESCRIPTION
**Pull request by marcovanleeuwen**
… which cause overlaps

See above, these are some fixes/updates to V0+ in AliFITv8.

Best regards,

Marco.

### CODE REVIEW

**Comment by chiarazampolli** [comment]
I guess this was already discussed with @AllaMaevskaya (she is watcher), I will approve.

**Comment by chiarazampolli** [comment]
+1

**Comment by chiarazampolli** [comment]
Apparently I cannot... I will check.

Chiara

**Comment by ktf** [comment]
+test

**Comment by ktf** [comment]
+1

**Pull request merged**
