### PR TITLE
 Added charmed "hyper"nuclei currently discussed in the ITS3 upgrade

### PR DESCRIPTION
**Pull request by bdoenigu**
Hi,

I have added the charmed "hyper"nuclei we are discussing in the MC preparation of the ITS3 studies to AliPDG and AliMC.

Cheers,
Benjamin

### CODE REVIEW

**Comment by ktf** [comment]
@chiarazampolli this has been open for 20 days. Is it actually needed?

**Comment by ktf** [comment]
+test

**Comment by ktf** [comment]
+test

**Comment by chiarazampolli** [comment]
Ciao @ktf ,

I don't know, it was not discussed within the DPG (or JIRA) as far as i know. I think @bdoenigu should comment. I guess it is still open due to holiday time.

Chiara

**Comment by bdoenigu** [comment]
Hi,

as far as I understood Andrea Dainese, there are at least two MC productions for the ITS3 LoI and a future TDR planned where in one the particles I added will be injected.

Cheers,
Benjamin

**Comment by chiarazampolli** [comment]
+test

**Comment by chiarazampolli** [comment]
Retrying...

**Pull request merged**
