### PR TITLE
Use AliTPCCommon code in common with O2

### PR DESCRIPTION
**Pull request by davidrohr**
Use the tracking code from AliTPCCommon for the HLT TPC CA GPU Tracking (+related changed and removal of the old code from AliRoot), Add global cmake option ALIROOT_ONLINE_MODE to disable non-online modules on all EL6 builds.

### CODE REVIEW

**Comment by dberzano** [comment]
+test **PLEASE DO NOT MERGE UNTIL MONDAY!**

**Comment by dberzano** [comment]
@davidrohr for the future:

* Please use a meaningful title describing in <50 chars what this PR does in this repo only
* Use the next lines for a more extended explanation
* Reference other PRs on other repos in a more appropriate way, _i.e._ alisw/alidist#1135

Thanks!

**Comment by davidrohr** [comment]
@dberzano : Can you start the testing again please? Is there actually any way I can start the validation?

**Comment by shahor02** [comment]
+test

**Comment by dberzano** [comment]
+1

**Pull request merged**
