### PR TITLE
Fix primary vertex position generation in AliGenPileup

### PR DESCRIPTION
**Pull request by fprino**

### CODE REVIEW

**Comment by chiarazampolli** [comment]
+1

**Comment by chiarazampolli** [comment]
Hello @shahor02 @ktf,

My approval is not enough, could you give a +1?

Cheers,

Chiara

**Comment by shahor02** [comment]
+1

**Comment by chiarazampolli** [comment]
Pinging @ktf , @MichaelLettrich also here, no idea what the problem with macos is now... 

Chiara

**Pull request merged**
