### PR TITLE
 Fix for aligenmc+AliDPG: protection for particle==NULL 

### PR DESCRIPTION
**Pull request by miweberSMI**

### CODE REVIEW

**Comment by chiarazampolli** [comment]
Dear @qgp , 

Do you agree with these changes?

Cheers,

Chiara

**Comment by miweberSMI** [comment]
Dear @chiarazampolli, @qgp, all,

we also had some discussion on https://alice.its.cern.ch/jira/browse/ALIROOT-7920, because it is indeed strange to obtain NULL pointers at all. If anybody has a good idea, what to check in order to find out what is going on there, I am happy to test this!
Once we have the PR merged, we should probably also merge AliDPG to master and do a full test...

Cheers,
Michael

**Comment by dberzano** [comment]
+test (I am testing the C.I., this is not an approval)

**Comment by dberzano** [comment]
The macOS error should go away in a while.

**Comment by miweberSMI** [comment]
Dear all,

by accident I pushed another commit here (just reverted it). @qgp, do you think you could approve the actual PR?

Thanks and cheers,
Michael

**Comment by qgp** [comment]
+1

**Pull request merged**
