### PR TITLE
fix NxN clusterizer to avoid low energy cells passing the min and seed cuts (F. Bock & N. Schmidt)

### PR DESCRIPTION
**Pull request by gconesab**

### CODE REVIEW

**Comment by gconesab** [comment]
+1

**Comment by gconesab** [comment]
Hello @ktf 
This commit seems stuck, can something be done to merge it?
Thanks!

**Comment by ktf** [comment]
Hi. The reason is yet one more python2 script which stopped working. I just moved it to python3 and things seems to be back in business..

**Comment by gconesab** [comment]
Thanks @ktf !

**Pull request merged**
