### PR TITLE
Port new HLT changes to prod

### PR DESCRIPTION
**Pull request by dberzano**
@davidrohr @mkrzewic reopened...

### CODE REVIEW

**Comment by dberzano** [comment]
@davidrohr can you approve?

**Comment by davidrohr** [comment]
+test

**Comment by davidrohr** [comment]
@mkrzewic : Can you have a look, I cherry-picked all commits from hlt/prod that were not yet in master, to get a consistent state.

**Comment by dberzano** [comment]
(And thanks for your patience about the PR bug.)

**Comment by mkrzewic** [comment]
+1

**Pull request merged**
