### PR TITLE
added reader for Les Houches event record format

### PR DESCRIPTION
**Pull request by hcab14**

### CODE REVIEW

**Comment by dberzano** [comment]
+test

**Comment by rbertens** [comment]
+1 Hi @hcab14 , this looks very nice. As this is code that could potentially be useful for other analysers, would it be possible to have e.g. a JIRA ticket with some validation plots to make sure that the parser output is valid? (or maybe a presentation exists already somewhere)? thanks

**Comment by dberzano** [comment]
Apologies for the noise (many identical emails), my bad.

**Comment by hcab14** [comment]
Hi @rbertens,

thanks for your comment.

I have created [ALIROOT-7239](https://alice.its.cern.ch/jira/browse/ALIROOT-7239)

**Pull request merged**
