### PR TITLE
[ALIROOT-8649] Restore porting the event weight to the pythia header

### PR DESCRIPTION
**Pull request by mfasDa**

### CODE REVIEW

**Comment by mfasDa** [comment]
@amorsch Can I safely assume the event weight in the pythia generator event header is not used by anyone else during the event generation? I have ported the code according what I found in the pure PYTHIA6 case (AliGenPythia).

**Comment by amorsch** [comment]
> @amorsch Can I safely assume the event weight in the pythia generator event header is not used by anyone else during the event generation? I have ported the code according what I found in the pure PYTHIA6 case (AliGenPythia).

Yes, this is OK.

**Comment by chiarazampolli** [comment]
@mfasDa : I am not an expert, but considering @amorsch answer, and checking the code, it looks fine to me. So I am giving a "+test" for now, will approve if all is fine.

**Comment by chiarazampolli** [comment]
+test

**Comment by chiarazampolli** [comment]
+1

**Pull request merged**
