### PR TITLE
PWGPP-538 - new function AliTreePlayer::MakeCacheTreeChunk for caching

### PR DESCRIPTION
**Pull request by miranov25**

### CODE REVIEW

**Comment by miranov25** [comment]
+1

**Comment by chiarazampolli** [comment]
+1

**Comment by chiarazampolli** [comment]
Failure like in the other PR: https://github.com/alisw/AliRoot/pull/1167
Should we merge it, @ktf , @shahor02 ?

Chiara

**Comment by shahor02** [comment]
Should not we wait for macos CI?

**Comment by chiarazampolli** [comment]
Yes, it was a comment about the release failure. Sorry i was not clear.

**Comment by chiarazampolli** [comment]
Hello all,

Both macos and release fail in G4:

```
I-TObject::SetNavigator: TG4RootNavigator created and registered to G4TransportationManager
isMaster=1

-------- EEEE ------- G4Exception-START -------- EEEE -------
*** G4Exception : PART70000
      issued by : G4NuclideTable
G4ENSDFSTATEDATA environment variable must be set
*** Fatal Exception *** core dump ***

 *** Break *** segmentation violation
Function simG4() busy flag cleared
Function Config() busy flag cleared
Warning in <TEnvRec::ChangeValue>: duplicate entry <Unix.*.Root.DynamicPath=.:$(ROOT_DYN_PATH):> for level 0; ignored
```

Maybe @ihrivnac  has some ideas? 
It is not related to this PR specifically, we have the same problem in https://github.com/alisw/AliRoot/pull/1167, which was merged. I propose to merge this too by hand.

Chiara

**Comment by ihrivnac** [comment]
@chiarazampolli ,

I am looking at the problem with G4ENSDFSTATEDATA since this morning. It looks that it is caused by the last fix in Geant4 module files (though the CI tests for the PR with this fix, including AliRoot, passed ok). As any change in alidist/geant4.sh requires rebuild of geant4, it takes time to investigate ...

**Comment by chiarazampolli** [comment]
Hello @ihrivnac ,

@ktf said that the tests would have been run automatically again after your PR, so they did successfully (before that, they were failing). Which means that your fix worked - many thanks! To be seen on lxplus, then, when we load the environment, right?

Chiara

**Pull request merged**
