### PR TITLE
Configurability of studied triggers

### PR DESCRIPTION
**Pull request by ddobrigk**

### CODE REVIEW

**Comment by mkrzewic** [comment]
+test

**Comment by mkrzewic** [comment]
is that the only thing that is needed?

**Comment by ddobrigk** [comment]
@mkrzewic , it is the only urgent thing. You also need to swap the processing macro for a new version (see my mail just now). All remaining adjustments we can do only in the post-processing macro or even with the info in the logbook (and I don't want to go nuts with component changes at the last minute!) - but from what I understand configurable triggers are absolutely mandatory...

**Comment by mkrzewic** [comment]
btw also here it would probably make sense to add the trigger names to the titles for reference

**Comment by ddobrigk** [comment]
Hi @mkrzewic , of course a good idea. Now implemented. Thanks! 

It may also be good to have the triggers printed also in the post-processing macro titles. Will send by mail...

**Comment by mkrzewic** [comment]
+1

**Pull request merged**
