### PR TITLE
Order by flavour the partons that are first and second mother of a hadron

### PR DESCRIPTION
**Pull request by fprino**
This PR fixes a behaviour that was observed with Pythia8, namley that about 50% of the charm and beauty hadrons did not have a charm (beauty) quark as parent, see https://alice.its.cern.ch/jira/browse/ALIROOT-8371.
This was traced back to the fact that in the tree of particles produced with Pythia8, the hadrons have a first and a second mother, and in 50% of the cases the quark having the same flavour (charm or beauty) of the hadron was the second mother, which is not propagated to the Kine Tree.
With the modification of this PR, a piece of code is added in AliGenPythiaPlus to swap the first and second mother in order to have as first mother the one having the same flavour of the hadron. When this is not possible (very rare cases) the first mother is chosen as the one with higher pdg code, i.e. a gluon if one of the two is a gluon, otherwise a t, b, c quark etc.

Best, Francesco

### CODE REVIEW

**Comment by chiarazampolli** [comment]
Hello @amorsch ,
If this change is ok for you, I would merge it.
Cheers,

Chiara

**Comment by amorsch** [comment]
+1

**Comment by chiarazampolli** [comment]
+1

**Comment by fprino** [comment]
Hi @ktf,

can you please check if the issue with the error in the test can be recovered?

Thanks!

Cheers, Francesco

**Comment by fprino** [comment]
Hi @ktf 

can you please have a look to this error?

Thanks, Francesco

**Comment by fprino** [comment]
Dear @ktf and @MichaelLettrich,

this PR seems stuck in build/AliRoot/macos.
Can you please have a look?
Thanks!

Ciao, Francesco

**Comment by ktf** [comment]
I've restarted the test. The fix in alidist in principle is now there.

**Comment by MichaelLettrich** [comment]
Seems to me like the execution of the tests fails on macos. @fprino. Can you have a look?

**Comment by chiarazampolli** [comment]
Hello @MichaelLettrich , 

I don't think it is something related to this PR, because others have similar issues, e.g. https://github.com/alisw/AliRoot/pull/1091

Cheers,

Chiara

**Pull request merged**
