### PR TITLE
Fix for AliCaloCalibSignal for EMCAL-213

### PR DESCRIPTION
**Pull request by loizides**
https://alice.its.cern.ch/jira/browse/EMCAL-213

### CODE REVIEW

**Comment by chiarazampolli** [comment]
Ciao @loizides ,

Is this the fix for the OCDB you told me about?

Cheers,

Chiara

**Comment by loizides** [comment]
Hi, but I accidentally committed two changes, only the 2nd is needed. Markus will help me tomorrow to remove it (I wish we still had svn...) 
Then I still need to test this, waiting for a file from Martin...

**Comment by mfasDa** [comment]
@loizides  Small comment: Please add the ticket ID [EMCAL-213] to the commit message and change title of the PR to "[EMCAL-213]: ... " in order to get the PR linked in JIRA to the corresponding JIRA ticket.

Cheers

Markus

**Comment by loizides** [comment]
+test

**Comment by loizides** [comment]
Have merged but now we still want to do some tests before asking for the porting request.

**Comment by dberzano** [comment]
@loizides you haven't merged - the message says you should approve with `+1` _after_ tests are completed _("If testing succeeds, merging will require further approval from...")_.

If you want your PR to be merged right after tests are OK, you should use `+1` from the start instead of `+test` 🙂

**Comment by loizides** [comment]
+1

**Comment by loizides** [comment]
Sorry I am a bit lost, is this now also ported, or do I have to request it? Constantin

**Comment by chiarazampolli** [comment]
This went automatically in v5-09-32 as the tag was done after the merging of the pull request.

Chiara

**Pull request merged**
