### PR TITLE
ALIROOT-7487: Add options to force Lc decay channel in AliPythia

### PR DESCRIPTION
**Pull request by jezwilkinson**
Adds options to AliDecayerPythia to allow forcing of Lc->pKpi or Lc->pK0S for dedicated MC productions (Jira ticket ALIROOT-7487)

### CODE REVIEW

**Comment by qgp** [comment]
+test

**Comment by jezwilkinson** [comment]
@dberzano Hello, I don't understand the origin of the alibuild error that appeared here - and both before and a short time after it appeared, the status said "all checks have passed" ("all checks passed", then the error appeared and it said "failed" for a couple of hours, but then succeeded again without any changes being made). Do you know what the cause of the issue could have been, and whether any action needs to be taken on this commit?
Thanks.

**Comment by dberzano** [comment]
@jezwilkinson sometimes we have temporary errors, due to timeouts or external factors. They clear out automatically after a while, as it happened in this case (all tests are now green), so please ignore them :-)

**Comment by jezwilkinson** [comment]
@dberzano Ok, thanks for the explainer!

@qgp & @rbertens would it be possible to go ahead with the merge, or is there anything left to be checked? This feature is a blocker for the MC productions planned in the attached Jira ticket, so please let me know if there's something still missing.

**Comment by rbertens** [comment]
hi @jezwilkinson , I think all is OK, but I'd like to give @qgp  a few hours to take a (renewed) look. If there's no objections I'll approve later today

**Comment by rbertens** [comment]
+1

**Comment by dberzano** [comment]
Apologies for the multiple bot comments, it was a glitch that kept redeploying our bot over and over.

**Pull request merged**
