### PR TITLE
expose some variables publicly for next version of AliTPCCommon

### PR DESCRIPTION
**Pull request by davidrohr**

### CODE REVIEW

**Comment by davidrohr** [comment]
@shahor02: could you type +1?

**Comment by shahor02** [comment]
+1

**Comment by davidrohr** [comment]
@dberzano : Could you merge this and include in the next AliRoot tag. The new interface is needed for the next major tag of AliTPCCommon.

Btw: can it be that you do not receive my e-mails? I have sent to you multiple times wrt. to this PR but not received a response, but I see that you are working.

**Comment by shahor02** [comment]
+1

**Comment by davidrohr** [comment]
@dberzano : sorry, I messed this up and pushed to the wrong branch..., can you type +1 again.

**Comment by davidrohr** [comment]
+1

**Pull request merged**
