### PR TITLE
Sync AliGPU from O2

### PR DESCRIPTION
**Pull request by davidrohr**

### CODE REVIEW

**Comment by davidrohr** [comment]
+test

**Comment by davidrohr** [comment]
+test

**Comment by davidrohr** [comment]
+test

**Comment by davidrohr** [comment]
@martenole : This AliRoot version seems to work finally :| Corresponding PR in O2 is AliceO2Group/AliceO2#3738

**Comment by davidrohr** [comment]
+test

**Comment by davidrohr** [comment]
@chiarazampolli @ktf @MichaelLettrich : What is the status of the MacOS CI for AliRoot? Is it not running anymore?

**Comment by chiarazampolli** [comment]
I know @MichaelLettrich worked on it, but I don’t know the details. He or @ktf can comment.

**Comment by ktf** [comment]
@MichaelLettrich did you rename back the tests?

**Pull request merged**
