### PR TITLE
STARLIGHT update to r313 and modifications for phi->KK (by srklein)

### PR DESCRIPTION
**Pull request by hcab14**
Please do not merge yet, I'm waiting for feedback from srklein@lbl.gov,  ahamdi@lbl.gov, mploskon@lbl.gov.

### CODE REVIEW

**Comment by hcab14** [comment]
This PR is ready to be merged.

**Comment by chiarazampolli** [comment]
I am not an expert on STARLIGHT, so I trust @hcab14 and approve.

**Comment by chiarazampolli** [comment]
+1

**Comment by hcab14** [comment]
@chiarazampolli Thank you!

**Pull request merged**
