### PR TITLE
Added two more particles (Hyperhelium-5 and Double-Hyperhydrogen-4) f…

### PR DESCRIPTION
**Pull request by bdoenigu**
…or the production in view of Run3/4 to AliMC and AliPDG (https://alice.its.cern.ch/jira/browse/UPG-10)

### CODE REVIEW

**Comment by dberzano** [comment]
+test

**Comment by dberzano** [comment]
Please ignore the log error message, it was me performing a test.

**Comment by dberzano** [comment]
By the way is this still in progress? Looks rather harmless to me but I'd prefer if it was approved by some experts on the subject.

**Comment by bdoenigu** [comment]
In principle Andeas Morsch was always having his hand on this class, but he is actually not in the list of people involved. It is still needed for the upcoming production for the upgrade physics studies...

**Comment by dberzano** [comment]
@amorsch can you please confirm we can merge this? Thanks!

**Comment by amorsch** [comment]
+1

**Comment by sawenzel** [comment]
+1 
(since @amorsch approved)

**Pull request merged**
