### PR TITLE
add option 'addPCMV0s' for ESD Filter

### PR DESCRIPTION
**Pull request by m-c-danisch**

### CODE REVIEW

**Comment by dberzano** [comment]
+test

**Comment by dberzano** [comment]
@m-c-danisch is this the V0 change we were talking about via email? Can you please open, also, a ticket on our JIRA (of type "Porting request") by specifying the need to port this pull request (number 229) to the next release (set "Fix version(s)" to v5-09-09)? This helps us (me, @chiarazampolli, etc.) to keep track of the important changes that will go to the next release.

Once this is merged I will start the release validation right away.

**Comment by m-c-danisch** [comment]
@dberzano yes, this is the change that I also sent via e-mail. I opened a JIRA ticket here: https://alice.its.cern.ch/jira/browse/ALIROOT-7320 I just realized that I did not really add any description, is this needed in the JIRA ticket? The approval of the corresponding aliphysics change is also ongoing: https://github.com/alisw/AliPhysics/pull/1221

**Comment by dberzano** [comment]
What we have in JIRA is OK. We just need one of the mentioned persons to quickly `+1` this pull request if it's OK (me, I cannot really judge its contents).

**Comment by pzhristov** [comment]
@m-c-danisch 

Hi Meike, 

I see you add two pointers to TBits objects:

+  TBits* 	     fbitfieldPCMv0sA;		   // Bitfield with PCM v0s from on-fly v0 finder
+  TBits* 	     fbitfieldPCMv0sB;		   // Bitfield with PCM v0s from offline v0 finder

and you set them to NULL, but I do not see where you create these objects. How is this supposed to work? Another comment: probably in your working group you all know what the abbreviation PCM means, however it would be good to specify it for the others.

Cheers,
Peter

**Comment by dberzano** [comment]
@pzhristov @m-c-danisch aren't they obtained from `AliAnalysisTask::GetInputData()`? Looks fine to me.

**Comment by m-c-danisch** [comment]
Hi @pzhristov ,
thanks for your comment.
They are filled via fbitfieldPCMv0sA = (TBits*) GetInputData(1); and this input is connected to the task in the AddTaskESDfilter. This input again is received as container from the analysismanager. That container again comes from the output of AddTask_ConversionAODProduction (in aliphysics: https://github.com/alisw/AliPhysics/pull/1221)
hope that helps with the understanding
Best regards
Meike

**Comment by dberzano** [comment]
News on the approval of this PR?

**Comment by pzhristov** [comment]
@m-c-danisch 
 OK, so we have two related pull requests: one in AliRoot and the second in AliPhysics. Last question: did you check if the size of the output is reasonable?

**Comment by pzhristov** [comment]
+1

**Comment by dberzano** [comment]
@pzhristov thanks for approving this: so I am going to start the release validation, finally!

**Comment by m-c-danisch** [comment]
@pzhristov yes, the AOD size will be reduced by ~20% because it will be possible now to use the V0filter without loosing PCM V0s

**Pull request merged**
