### PR TITLE
corrections for information from AMPT: number of hard scatterings and…

### PR DESCRIPTION
**Pull request by amorsch**
… optical glauber (profile)

### CODE REVIEW

**Comment by amorsch** [comment]
Both are corrections in common blocks / corresponding c++ structure
- wrong common block name in profile.f
- wrong order of variables in Acommon.h

**Comment by amorsch** [comment]
> Both are corrections in common blocks / corresponding c++ structure
> 
> * wrong common block name in profile.f
> * wrong order of variables in Acommon.h
In addition the function gauss3 and gauss4 were used from the HIJING library (lazy binding). This does not work on MacOS.
They have been now added to libAMPT directly.

**Comment by maireiphc** [comment]
+test

**Comment by maireiphc** [comment]
Hello Andreas,
  sthg not clear for me : "This does not work on MacOS." meaning that it was not working on MacOS or that your fix will not work under MacOS ? In such case, what is the next move : we merge into AliRoot and see ? or we wait since you have at hand a coming fix for Mac0S ?

Cheers,
   Antonin

**Comment by amorsch** [comment]
> Hello Andreas, sthg not clear for me : "This does not work on MacOS." meaning that it was not working on MacOS or that your fix will not work under MacOS ? In such case, what is the next move : we merge into AliRoot and see ? or we wait since you have at hand a coming fix for Mac0S ?
> 
> Cheers, Antonin

Hi Antonin, 
sorry, I was not very clear. After upgrading to Big Sur, the updated macro fastGenAmpt.C did not work anymore, because it couldn't find the gauss3 and gauss4 functions. I found out that these were indeed only defined in libHIJING. 
Including these functions into libAMPT solves the problem. 
Cheers
Andreas

**Comment by maireiphc** [comment]
+1

**Comment by chiarazampolli** [comment]
Hi @amorsch , @maireiphc , 

Can I approve it?

Chiara

**Pull request merged**
