### PR TITLE
Modify TriggerSTU,TriggerTRU to not run the trigger simulation if the thresholds…

### PR DESCRIPTION
**Pull request by moliver813**
… are missing.

Error messages given during TriggerElectronics creation.

### CODE REVIEW

**Comment by mfasDa** [comment]
+test

In my opinion OK, this change will lead to no patches when having unexpected behavior (0-threshold in OCDB), which should be catastrophic enough to make people aware of problems.

**Comment by mfasDa** [comment]
+1

As the PR was open a sufficient time and the change looks OK I approve it. Build errors seem to be unrelated to the commit. One remark: To better keep track of PR it would be good to add a JIRA ticket Number if available (linked to ticket - here it is) at the beginning of the PR.

@moliver813 @gconesab Do we need to back port to versions older than master (i.e. patches branches)?

**Comment by gconesab** [comment]
Hello @moliver813 and @mfasDa 

I though we said we would call an AliFatal, if I am not wrong, this commit will create tons of messages with AliError not solving the issue if the logs are not checked and keep reasonable sizes.

Regards ... Gustavo

**Comment by mfasDa** [comment]
Hi @gconesab ,

Indeed we agreed on AliFatal, thanks for spotting! @moliver813 , could you please move the AliErrors to AliFatals?

Cheers

Markus

**Comment by moliver813** [comment]
Yeah, I can make that change.  I also tried to make sure my errors only occurred at the beginning of a simulation, but I apparently I didn't do that for the L0 error messages.  What if only a single TRU is missing a threshold?  Should I still call an AliFatal?  I assume yes, since that would produce either invalid results, or cause the L0 bug again.

**Comment by mfasDa** [comment]
Yes, it should crash with an AliFatal rather then give invalid results.

**Comment by gconesab** [comment]
Hello, @moliver813 
I have not seen the implementation of the fatal?
Thanks ... Gustavo

**Pull request merged**
