### PR TITLE
latest changes to online vzero HLT calib component

### PR DESCRIPTION
**Pull request by ddobrigk**

### CODE REVIEW

**Comment by davidrohr** [comment]
Hi @ddobrigk : FYI: You could have done a forced push to the old PR, instead of opening a new one.

**Comment by davidrohr** [comment]
+test

**Comment by mkrzewic** [comment]
+1 looks good, let's merge and test with data

**Comment by davidrohr** [comment]
+1 OK, will wait for the EMCAL changes today, and then try to update the software at next beam dump.

**Pull request merged**
