### PR TITLE
Update the FIT geometry to match the latest developments in O2

### PR DESCRIPTION
**Pull request by iarsene**

### CODE REVIEW

**Comment by iarsene** [comment]
These changes are needed in order to have the same FIT geometry in Aliroot, needed for FOCAL performance simulations. The changes were prepared by Hadi Hassan and Edmundo Garcia. I tested them, and the new code compiles and runs properly.

**Comment by chiarazampolli** [comment]
+1

**Comment by chiarazampolli** [comment]
+1

**Comment by chiarazampolli** [comment]
+test

**Comment by chiarazampolli** [comment]
+test

**Comment by chiarazampolli** [comment]
+test

**Comment by chiarazampolli** [comment]
+test

**Comment by chiarazampolli** [comment]
+test

**Comment by iarsene** [comment]
@chiarazampolli , @TimoWilken, @ktf 
I checked the Aliroot/o2 test log, and the build succeeds. After that there are some test simulations being run, and some of them seem to crash but these are I think from reasons which are unrelated to the updates in this PR. We are touching just the FIT geometry, which is not even included in these test simulations from what i can understand.
Then, the "release" test is still failed, but this is the one still using root5, which i guess we agreed to take out. So, could you have a look on your side, so that we can progress with this PR.
Cheers, Ionut

**Comment by chiarazampolli** [comment]
Hello @ktf , 
The error is:
```
E-AliDataFile::GetFileName: Data file not found on any location (use environment variable $ALICE_DATA to manually specify one): "OADB/COMMON/PID/data/TPCPIDResponseOADB.root"
W-AliPIDResponse::ExecNewRun: No TPC response parametrisations found using the new method. Falling back to the old method.
E-TFile::TFile: file /OADB/COMMON/PID/data/TPCPIDResponse.root does not exist
E-TFile::TFile: file /OADB/COMMON/PID/data/TPCvoltageSettings.root does not exist
F-AliPIDResponse::SetTPCPidResponseMaster: Could not retrieve the TPC pid response from: $ALICE_PHYSICS/OADB/COMMON/PID/data/TPCPIDResponse.root
F-AliPIDResponse::SetTPCPidResponseMaster: aborting execution due to AliFatal
mv: cannot stat ‘*.rndm’: No such file or directory
++ WITHESDCHECK=
```
I don't know if there is still an issue with ALICE_PHYSICS, but I would merge this now.
Chiara

**Comment by iarsene** [comment]
@ktf, @TimoWilken, @chiarazampolli 
The AliRoot/o2 check crash does not seem to be related to the changes in the PR, while the release test we agreed to remove it. Are there other issues which need to be considered? Otherwise it would be very useful to merge this PR, thanks

**Comment by chiarazampolli** [comment]
Hi @iarsene , all.

As i wrote the other day, I would also merge.

cheers,

Chiara

**Comment by TimoWilken** [comment]
OK, merged.

**Pull request merged**
