### PR TITLE
Port to V5 09 56 patches Updating the mass of exotic bound states (#1472)

### PR DESCRIPTION
**Pull request by gconesab**

### CODE REVIEW

**Comment by gconesab** [comment]
> Ciao @gconesab ,
> 
> There seems to be conflicts with this PR, can you check?
> 
> Chiara

Ciao, only the commit of interest is merged, see "files changed", so I do not see the conflict.

**Comment by chiarazampolli** [comment]
I don't know what the problem is, maybe @TimoWilken , @ktf , @pzhristov have an idea? github says there are conflicts to solve:
Screenshot 2023-05-08 at 22 22 22

**Comment by TimoWilken** [comment]
Screenshot_20230508-163347_Fennec

Looks fine to me. Shall I merge it?

**Comment by gconesab** [comment]
I will close and restart

**Pull request closed without merging**
