### PR TITLE
First commit of ESD Calo Friends cf. EMCAL-195

### PR DESCRIPTION
**Pull request by guernane**

### CODE REVIEW

**Comment by shahor02** [comment]
+test

**Comment by shahor02** [comment]
@guernane : looks like you did not push the AliESDCalofriend.cxx file

**Comment by guernane** [comment]
@shahor02 : the missing files are now in, sorry for the inconvenience. Markus suggested me to rewrite the history squashing the 3 commits which I can do if needed.

**Comment by mfasDa** [comment]
Hi @guernane, 

yes, please try to squash first. It makes life easier. More compact histories are usually easier to handle, in particular when going back in the past in order to spot any issue.

Cheers

Markus

**Comment by mfasDa** [comment]
@gconesab For JIRA have the ticket ID somewhere in the commit message + PR title is sufficient to have the tickets linked. If you look at the ticket the commit and the PR got linked. Using the tag in the commit header is not strictly mandatory for the bot to link PR and ticket but helps readability + searching in the git log. It is only important to have the full ticket ID (here EMCAL-195), i.e. something like "Fix stuff discussed in ticket 195 ..." will not work.

**Comment by gconesab** [comment]
@mfasDa  OK thanks for the clarification, I misunderstood your previous warnings in other commits.

**Comment by shahor02** [comment]
+test

**Comment by shahor02** [comment]
+1

**Pull request merged**
