### PR TITLE
Port updates for f0 resonances to V5 09 56 patches

### PR DESCRIPTION
**Pull request by gconesab**

### CODE REVIEW

**Comment by gconesab** [comment]
please approve @pzhristov, @chiarazampoll, @shahor02 and please @TimoWilken  merge when done

**Comment by gconesab** [comment]
Thanks @TimoWilken, can you tag?

**Comment by TimoWilken** [comment]
I can merge this right away, since it's for the patches branch! Do you need a tag right away or is there more to come?

**Comment by TimoWilken** [comment]
Tagged v5-09-56v. Almost at "z", looks like we'll run out of single letters soon...

**Pull request merged**
