### PR TITLE
K0L stable in decaytable and protection against changes in AliDecayerPythia

### PR DESCRIPTION
**Pull request by amorsch**
see also 
https://alice.its.cern.ch/jira/browse/ALIROOT-6940

### CODE REVIEW

**Comment by chiarazampolli** [comment]
+1

**Comment by FriederikeBock** [comment]
@amorsch how would we then for the cocktail allow this decay, as we need it for the corrections for the pi0's (which was the reason @laltenka had put it like this)

**Comment by chiarazampolli** [comment]
@FriederikeBock , so this was intentional?

**Comment by FriederikeBock** [comment]
@chiarazampolli, let's say semi-intentional. We need to be able to let Pythia decay those particles if asked to do so and I guess @laltenka saw this as the easiest way to do this, without being aware of the implications this has for other purposes. Sorry for causing so many troubles.

**Comment by chiarazampolli** [comment]
Ok, I see. Note that I approved this PR, and it was merged. 

Chiara

**Comment by amorsch** [comment]
@FriederikeBock 
you can use 
AliDecayerPythia::DecayLongLivedParticles()
I suppose you take into account the decay vertex in some way. Most of the K0L
get absorbed before they actually decay I would guess.
Andreas

**Pull request merged**
