### PR TITLE
added Lambda and Omega pp5 realistic shapes

### PR DESCRIPTION
**Pull request by bianchil**

### CODE REVIEW

**Comment by catalinristea** [comment]
Dear all,

Could anybody have a look over this commit, and approve it?
It is currently needed by https://alice.its.cern.ch/jira/browse/ALIROOT-8821

Thanks and kind regards,
Catalin.

**Comment by bianchil** [comment]
Hi @chiarazampolli ,
the value 1 means that the rapidity is set to be randomly generated flat. It will not acquire the value 1 each time.
Cheers
Livio

**Comment by chiarazampolli** [comment]
Thanks for the clarification. I will now approve.
+1

**Comment by chiarazampolli** [comment]
+1

**Comment by bianchil** [comment]
Ciao @chiarazampolli ,
this is failing for a reason that I don't understand and apparently not connected to the code I committed. 
Do you have any hint on the reason? Checking the logs it seems something connected to AliHLTComponentHandler ?
Everything runs smoothly in my local updated AliRoot version...
Sorry for bugging you on this
L

**Comment by bianchil** [comment]
Hi @TimoWilken ,
do you have an idea of the issue reported here? Apparently it seems not connected to the code itself..
Apologies (and please discard) if it is not you to ping for this.
Cheers
Livio

**Comment by TimoWilken** [comment]
Hi @bianchil, you're right, the CI failures are unrelated. I've merged this PR manually.

**Pull request merged**
