### PR TITLE
Forcing Ds-reso decay and fixing track transport

### PR DESCRIPTION
**Pull request by stefanopolitano**
This PR implements forced decay for D-meson resonances and resolves issues with their decay product track transport.
It is in response to the discussion documented here: https://alice.its.cern.ch/jira/browse/ALIROOT-8847.

### CODE REVIEW

**Comment by gconesab** [comment]
Hi @TimoWilken, another commit that will need to be ported. 
Can you merge it?
Cheers ... Gustavo

**Comment by gconesab** [comment]
Hi @TimoWilken,

another commit that needs to be ported, can you merge it?

Cheers ... Gustavo

**Comment by TimoWilken** [comment]
This PR is for the `master` branch, so it needs a +1 from one of the listed people! The porting PR against the appropriate -patches branch I can merge directly.

**Comment by gconesab** [comment]
OK then @pzhristov ?

**Comment by sustripathy** [comment]
+1

**Pull request merged**
