### PR TITLE
Force decay of f0(1500)

### PR DESCRIPTION
**Pull request by BongHwi**
f0(1500) is not defined in Pythia8 by default, hence I couldn't force the decay mode in the injector script.
Here I force the decay mode of f0(1500) while keeping the old decay mode information in the git history.

### CODE REVIEW

**Comment by BongHwi** [comment]
Dear @amorsch , Could you approve this modification? It's related to the JIRA ALIROOT-8826.

**Comment by amorsch** [comment]
Dear @BongHwi, usually we make the forcing of a decay mode configurable in AliDecayerPythia8. You method discards all other decay modes for all productions. Is this what we want ?

**Comment by BongHwi** [comment]
Dear @amorsch , thanks for pointing out that part. I’ve considered to apply it on the injector script but f0(1500) was not defined in Pythia8, thus I couldn’t pass the forced decay mode in the injector side. Is it possible to force the decay mode of this particle in the AliDecayerPythia8? If so, I’ll apply it.

**Comment by BongHwi** [comment]
Dear @amorsch ,
I couldn't confirm the decayer method in my local env. Maybe I can apply a similar method which was used by HF after.

But since this resonance is not injected by Pythia8 itself, and only studied by this decay mode and the injected MC is needed urgently, I would like to keep the current method.

I hope this is fine.

**Comment by amorsch** [comment]
Hi @BongHwi, I'm actually confused now. You mention Pythia8 but your modification concerns the decay table read by Pythia6. 
For Pythia6 the standard procedure would be to add a new decay type in /EVGEN/AliDecayer.h
and handle the case in 
AliDecayerPythia::ForceDecay
There are plenty of examples.

**Comment by amorsch** [comment]
+1

**Comment by BongHwi** [comment]
Hello @chiarazampolli  @jackal1-66  @jgrosseo 
Could you approve this PR? it's quite urgent.

Best regards,
Bong-Hwi

**Comment by chiarazampolli** [comment]
+1
Since Andreas approved it, I also do so.

**Comment by chiarazampolli** [comment]
+1

**Comment by BongHwi** [comment]
It's apparently an error not related to my PR.
Could you take a look at this @TimoWilken @ktf ?

Best regards,
Bong-Hwi

**Comment by TimoWilken** [comment]
Hi @BongHwi, a fix has just been merged in alidist, and I've restarted the check. Let me know if it still fails.

**Pull request merged**
