### PR TITLE
mods. for embedded MC labels + porting of extra variable to AOD

### PR DESCRIPTION
**Pull request by shahor02**

### CODE REVIEW

**Comment by shahor02** [comment]
+1

**Comment by shahor02** [comment]
Hi @dberzano , today I was getting invitations to approve others commits, but it looks Iike I cannot approve my own commit. Is there a problem with permissions?
Cheers,
 Ruben

**Comment by dberzano** [comment]
+test

You've changed more than 10 files, therefore approval falls back on us, but we plan to clarify this with a message and add you to the admins next week.

**Comment by ktf** [comment]
+1

**Comment by ktf** [comment]
@dberzano @jgrosseo @qgp I would say 10 files is really to little...

**Comment by jgrosseo** [comment]
Yes, I don't see the need for this limitation. And it was never discussed, please remove it.

**Comment by dberzano** [comment]
@jgrosseo we have already took care of it.

**Pull request merged**
