### PR TITLE
Implementing settings for MC Omegac0

### PR DESCRIPTION
**Pull request by ZFederica**

### CODE REVIEW

**Review by chiarazampolli — APPROVED** [review]

**Comment by chiarazampolli** [comment]
+1

**Comment by chiarazampolli** [comment]
Hello @TimoWilken , @ktf , 
Do you know what the error is related to?

**Comment by TimoWilken** [comment]
Hm, since v6-25 (which we use since alisw/alidist#4291), ROOT [only supports C++14 and up](https://github.com/alisw/root/blob/alice/v6-26-00-patches/cmake/modules/CheckCompiler.cmake#L167).

When building with `next-root6` defaults, our recipes have `CXXSTD=17` and `-std=c++11`, which confuses the ROOT recipe. alisw/alidist#4356 should fix this.

**Comment by chiarazampolli** [comment]
Hello @TimoWilken , 

What is the issue here? Do you know?

Thanks for the help!

Chiara

**Comment by TimoWilken** [comment]
Hi @chiarazampolli, see alisw/alidist#4356 (now merged). I've restarted the check.

**Comment by chiarazampolli** [comment]
Hello @TimoWilken , 

Thanks! But it is still failing, though somewhere else... 

Chiara

**Pull request merged**
