### PR TITLE
Converter fixes

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@pzhristov as discussed.

@TimoWilken can you please tag 57d once this passes?

**Comment by ktf** [comment]
+1

**Comment by ktf** [comment]
@TimoWilken why is this not being picked up yet?

**Comment by TimoWilken** [comment]
@ktf `list-branch-pr` is looking for PRs into the `master` branch only, but this is against `v5-09-57-patches`.

**Comment by pzhristov** [comment]
Should we squash and merge manually?

**Pull request merged**
