### PR TITLE
Avoid overlap with old ADA

### PR DESCRIPTION
**Pull request by ecalvovi**
Avoid overlap of air volume (voRB24CuTubeA) with old ADA

### CODE REVIEW

**Comment by pzhristov** [comment]
+test

**Comment by dberzano** [comment]
@pzhristov who can confirm this makes sense?

**Comment by pzhristov** [comment]
Hi @dberzano, I checked with Ernesto and the change is quite OK. I will approve the pull request.

**Comment by pzhristov** [comment]
+1

**Pull request merged**
