### PR TITLE
Allow for running tests outside ALICE environment

### PR DESCRIPTION
**Pull request by mfasDa**
Currently running ctest stand-alone requires initializing
the ALICE environment outside. Explicitly specifying PATH
and ROOTSYS are sufficient to launch ctest without
being in an ALICE environment.

### CODE REVIEW

**Comment by mfasDa** [comment]
Any problem with this? On the usual build test it doesn't hurt, but it can be quite useful.

**Comment by chiarazampolli** [comment]
Hello @ktf , 

Do you agree to approve?

Chiara

**Comment by mfasDa** [comment]
Would be good if at the same time also the corresponding pull request in AliPhysics could be processed: https://github.com/alisw/AliPhysics/pull/17042

**Comment by mfasDa** [comment]
At least launching the test would not harm ...

**Comment by mfasDa** [comment]
Let's see whether this will ever have a chance to be merged ...

The corresponding commit in AliPhysics is!

**Comment by ktf** [comment]
+1

**Pull request merged**
