### PR TITLE
Port HF and GA developments and fixes from master to v5-09-02

### PR DESCRIPTION
**Pull request by gconesab**
5bd4c35 // Make option to switch on long-lived decayse in PYTHIA8

dd038dc // Fix formatting requested in #PR260

 e16efd7 // Add documentation of the new settings

41ed0bb // Increasing classdef version

15c31da //  fixing include path for Pythia8 headers

3853038 // Correct use of decayer in AliGenPythiaPlus

2fe3357 //  fPythia object not persistent to avoid default constructur be called when reading galice.root

256cc79 // Fix index to have the CutOnChild selection working with Pythia8

9b44d76 // Implement kHeavyFlavor as option for SetSTackFillOpt

5c302ea // Update decay channels and BRs to force charm hadronic decays (#1078)

98275cc // Change to SoftQCD the process for HF generation (#1084)

e13e5fb // Order by flavour the partons that are first and second mother of a hadron

cfe3bce // debug printf removed

8235fc1 // debug printf removed

7e60b86 // Change PYTHIA8 to 8.243 (#997)

b8e0bc7 // Fix for newly imported Pythia8

1c15320 // Omega_ccc added.

2f1b95c // Update AliGenITSULib.cxx

d5a1485 // Adding Xic+->pK-pi+ (including Xic+->pK0*), Xic+->Xi-pi+pi+

bc50dad // Add HF selection case with c and b proportions as in Pythia (#1096)

dd9be9d // Overwrite default process (elastic scattering) from decayer initialis…

9b44d762 // Implement kHeavyFlavor as option for SetSTackFillOpt

90065ee // outgoing partons are in positions 4-5 and not 6-7 like in PYTHIA6

38ab721 //  apply the acceptance cuts on the physical direct photon and not on the first photon in the generation

a96c6d7 // add protection in case weird events with photons generating other particles are produced

236d5d3 // Add option to trigger particles over any of the central barrel calorimeter

0f6bbdf // Fix lambda_b lifetime in Pythia8

6aa2ace // switch pi0 decay on in pythia8 decayer

### CODE REVIEW

**Comment by chiarazampolli** [comment]
@ktf : also here, like in https://github.com/alisw/AliRoot/pull/1131, we have comments that appear twice. If you confirm that it is fine, I can squash and merge. 

Chiara

**Comment by gconesab** [comment]
The only commits double "debug printf removed" are in fact different commits, I do not think there are doubled commits here

**Comment by chiarazampolli** [comment]
I saw this:

> Implement kHeavyFlavor as option for SetSTackFillOpt

in your comment twice. And you have 28 commits, while in 38 there were 17... I will check the list of commits.

**Comment by gconesab** [comment]
I had to pick older commits compared to 24 or 38.

Gustavo

On 26 Mar 2020, at 16:42, chiarazampolli <notifications@github.com<mailto:notifications@github.com>> wrote:



I saw this:

Implement kHeavyFlavor as option for SetSTackFillOpt

in your comment twice. And you have 28 commits, while in 38 there were 17... I will check the list of commits.

**Comment by chiarazampolli** [comment]
@gconesab , you are right, no double commits. Merging.

**Comment by gconesab** [comment]
I missed the one on Implement kHeavyFlavor as option for SetSTackFillOpt, indeed I might have added it twice since there was a conflict at some point

Gustavo

On 26 Mar 2020, at 16:43, Gustavo Conesa Balbastre <Gustavo.Conesa.Balbastre@cern.ch<mailto:Gustavo.Conesa.Balbastre@cern.ch>> wrote:

I had to pick older commits compared to 24 or 38.

Gustavo

On 26 Mar 2020, at 16:42, chiarazampolli <notifications@github.com<mailto:notifications@github.com>> wrote:



I saw this:

Implement kHeavyFlavor as option for SetSTackFillOpt

in your comment twice. And you have 28 commits, while in 38 there were 17... I will check the list of commits.

**Pull request merged**
