### PR TITLE
EMCAL-408 fix AliEMCALSTURawStream decoder

### PR DESCRIPTION
**Pull request by guernane**
fix rho value and max gamma patch
add the missing GA digits in median mode

### CODE REVIEW

**Comment by guernane** [comment]
+test
still work in progress, don't yet merge

**Comment by dberzano** [comment]
+test

**Comment by dberzano** [comment]
+test

**Comment by mfasDa** [comment]
+1

For EMCAL

**Comment by chiarazampolli** [comment]
It seems ok to me. Can we merge? I ask to be 200% sure, after @guernane comment to wait (but now Markus approved for EMCAL, so probably it is fine).

**Comment by chiarazampolli** [comment]
PS @dberzano : I am receiving multiple mails about this PR... Do you know why?

**Pull request merged**
