### PR TITLE
Fix build on SLC6 for DAQ

### PR DESCRIPTION
**Pull request by dberzano**

### CODE REVIEW

**Comment by dberzano** [comment]
Please do not approve it yet, I am using it for testing a test!

**Comment by dberzano** [comment]
+test

**Comment by miranov25** [comment]
Hallo Dario.

I checked your modifications - ignoring space:
https://github.com/alisw/AliRoot/pull/195/files?w=1
I see no modification except of space. Was these reason for the SLC failure?

I have new version of script, I hope it will merge without problem

+1

**Comment by miranov25** [comment]
+1

**Comment by dberzano** [comment]
@miranov25 I thank you for approving that but my first comment clearly said not to merge this as I am currently using this pull request for testing the automatic tests - not a big deal though, I'll open a new one.

For the record: I am adding AliRoot test builds on native SLC6 as this is still required by DAQ. The relevant change here is the space in the nested "closing" template (`> >` instead of `>>`), which is unfortunately required by old GCC compilers.

**Comment by miranov25** [comment]
@dberzano I'm sorry I misunderstood message. 
In meantime I merged and pushed new version of AliDrawStyle, without whitespace and with some extensions.
https://github.com/alisw/AliRoot/pull/196
Not sure if it was the best way to proceed, but current code in git is correct for me.
I think we can close this ticket unless you want experiment further with SLC6

**Pull request merged**
