### PR TITLE
Fix D from Ds* topologies

### PR DESCRIPTION
**Pull request by fgrosa**

### CODE REVIEW

**Comment by gconesab** [comment]
Ciao @chiarazampolli hiara, I guess this can be approved?

**Comment by chiarazampolli** [comment]
+1

**Comment by gconesab** [comment]
Hi @TimoWilken , any idea of what is the problem here?

**Comment by TimoWilken** [comment]
Hi @gconesab, sorry, the Mac CI check is [currently broken](https://alice.its.cern.ch/jira/browse/O2-4171). While we're investigating, let me know if I should merge this PR once the Linux check succeeds.

**Comment by gconesab** [comment]
Hi @TimoWilken, thanks, then when linux succeeds I agree to approve.

**Pull request merged**
