### PR TITLE
Change PYTHIA8 to 8.243

### PR DESCRIPTION
**Pull request by ddobrigk**
This is up for review! Please do not approve unless the [corresponding discussion on JIRA](https://alice.its.cern.ch/jira/browse/ALIROOT-8321) has also converged and everything is fine.

### CODE REVIEW

**Comment by pzhristov** [comment]
I will approve the pull request as decided yesterday during the software and computing meeting.

**Comment by pzhristov** [comment]
+1

**Comment by ddobrigk** [comment]
I don't think there's any way around the fact that this will be a large commit (as it replaces PYTHIA8 inside AliRoot)... Could we maybe override the size restriction this one time? Thanks!

**Comment by davidrohr** [comment]
I think most of the size comes from the examples and from the documentation in the share folder. Wouldn't it make sense to remove these?

**Comment by pzhristov** [comment]
I propose to keep the code, the examples and the documentation as provided by the authors, so I will squash and merge manually.

**Comment by ktf** [comment]
Apparently this broke the build of AliRoot.

```
DEBUG:AliPhysics:AliRoot:v9-99-99: Warning: Error occurred during reading source files
DEBUG:AliPhysics:AliRoot:v9-99-99: Warning: Error occurred during dictionary source generation
DEBUG:AliPhysics:AliRoot:v9-99-99: !!!Removing /build/workarea/sw/20156052/1/BUILD/569dea7208cdb499821324b8ded69d7c552c5d44/AliRoot/PYTHIA8/AliPythia8/G__AliPythia8.cxx /build/workarea/sw/20156052/1/BUILD/569dea7208cdb499821324b8ded69d7c552c5d44/AliRoot/PYTHIA8/AliPythia8/G__AliPythia8.h !!!
DEBUG:AliPhysics:AliRoot:v9-99-99: Error: /build/workarea/sw/20156052/1/slc6_x86-64/ROOT/v5-34-30-alice10-29/bin/rootcint: error loading headers...
DEBUG:AliPhysics:AliRoot:v9-99-99: gmake[2]: *** [PYTHIA8/AliPythia8/G__AliPythia8.cxx] Error 1
DEBUG:AliPhysics:AliRoot:v9-99-99: gmake[1]: *** [PYTHIA8/AliPythia8/CMakeFiles/AliPythia8.dir/all] Error 2
DEBUG:AliPhysics:AliRoot:v9-99-99: gmake[1]: *** Waiting for unfinished jobs....
```

I am trying to reproduce...

**Pull request merged**
