### PR TITLE
Bug fix: EMCal misal matrices were not properly load.

### PR DESCRIPTION
**Pull request by aiola**
This bug was introduced by commit 88429ce92e7c55c8cadb223ade4d6628104f871b

### CODE REVIEW

**Comment by gconesab** [comment]
+test

**Comment by gconesab** [comment]
+1

**Comment by gconesab** [comment]
+1

**Comment by mfasDa** [comment]
@aiola Please remove the printfs and merge the message into one AliFatal

**Comment by gconesab** [comment]
I will take care of that.

**Pull request merged**
