### PR TITLE
Protection agains Distortion RMS paramet. < 0

### PR DESCRIPTION
**Pull request by shahor02**
Fix for the problem discussed in https://alice.its.cern.ch/jira/browse/ALIROOT-8418?focusedCommentId=245179&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-245179

### CODE REVIEW

**Comment by chiarazampolli** [comment]
Hello @ktf , 

Can you please check? The log is not available. 

Chiara

**Comment by ktf** [comment]
@MichaelLettrich can you check?

**Comment by MichaelLettrich** [comment]
based on the log, there was a glitch in building python-modules. The pr is currently being rebuilt and python modules was already compiled correctly.

**Comment by chiarazampolli** [comment]
Ciao @MichaelLettrich , 

Still errors, are they before your comment?

Chiara

**Comment by MichaelLettrich** [comment]
No, this is an error during the execution of the unit tests @chiarazampolli. I have no idea what causes them or how to fix them, but there have been errors since Christmas. The policy then has been to disable guntest https://alice.its.cern.ch/jira/browse/ALIROOT-8404. I reenabled them today to see if they still occur. Maybe @pzhristov  can comment how to proceed with this.

**Comment by MichaelLettrich** [comment]
@chiarazampolli: The issue is ours, so I will disable guntest again for the time being  and work with @pzhristov  to bring them back in a working manner.

**Pull request merged**
