### PR TITLE
New single injection per event mode

### PR DESCRIPTION
**Pull request by mpuccio**
Hi @amorsch ,
I added the modification to AliGenCocktail that we discussed yesterday.
The default behaviour does not change. The modifications are minimal but the fix of formatting makes them not very visible. Please check the diff without white spaces changes [here](https://github.com/alisw/AliRoot/compare/master...mpuccio:master?w=1) (or adding ?w=1 to the url of this page).
Cheers,
Max

### CODE REVIEW

**Comment by rbertens** [comment]
+1 thanks @mpuccio  for providing the diff without white space changes

**Comment by amorsch** [comment]
+1

**Comment by miweberSMI** [comment]
Hi @mpuccio, all,

could you just quickly explain, what the new functionality does? I assume you produce one particle per event, but from a larger "pool" of particles?

Thanks and cheers,
Michael

**Comment by mpuccio** [comment]
Ciao @miweberSMI ,

with this feature the first generator in the cocktail is considered as underlying event while all the others are the signal generators. For each event, enabling the SingleInjectionPerEvent flag, it generates the underlying event and one and only one of the other generators picked randomly.

Cheers,
Max

**Pull request merged**
