### PR TITLE
[ALIROOT-8821] added Lambda and Omega pp5 realistic shapes

### PR DESCRIPTION
**Pull request by gconesab**

### CODE REVIEW

**Comment by coppedis** [comment]
+1

**Comment by gconesab** [comment]
Hi @TimoWilken  and @ktf, is this test hanging due to the grid problems of the last days? Can it be somehow helped to end?
Thanks!

**Comment by gconesab** [comment]
Hi @TimoWilken,

maybe I have forgotten the procedure after new year, I have ported / cherry picked changes from master to this branch and now we want to tag this branch. The CI runs independently, isn't it?  If we can merge directly perfect, what I am missing?

Thanks ... Gustavo

**Comment by TimoWilken** [comment]
Hi @gconesab, thank you, in that case it should be fine. Merging.

**Pull request merged**
