### PR TITLE
Fix case where no DPMJET is found

### PR DESCRIPTION
**Pull request by dberzano**
DPMJET is disabled if neither external nor builtin DPMJET are found

### CODE REVIEW

**Comment by dberzano** [comment]
+1

**Comment by dberzano** [comment]
+1

**Comment by dberzano** [comment]
@qgp Do you agree with the patch? If so, and if it compiles, we can add it to upstream AliRoot.

**Comment by qgp** [comment]
@dberzano: thanks for the fix and, yes, I agree

**Pull request merged**
