### PR TITLE
Corrections in guard rings

### PR DESCRIPTION
**Pull request by MarekKowalski1504**
Added guard rings

### CODE REVIEW

**Comment by chiarazampolli** [comment]
Hello @ktf , 

What is exactly the status of this PR?

Thanks, and cheers,

Chiara

**Comment by MarekKowalski1504** [comment]
PR to |v5-09-02-devel-itsgeom 
<https://github.com/MarekKowalski1504/AliRoot/tree/v5-09-02-devel-itsgeom> 
is still pending tests.|

|Cheers, Marek
|

**Comment by chiarazampolli** [comment]
Ciao Marek, 

Yes, I know, but I wonder why... 

Cheers,

Chiara

**Comment by MarekKowalski1504** [comment]
Me too.

M.

**Comment by ktf** [comment]
We do not check PRs which are not done on master.

**Pull request merged**
