### PR TITLE
Fix compilation with root 6

### PR DESCRIPTION
**Pull request by raymondEhlers**
Trivial fix for compilation with root 6

### CODE REVIEW

**Comment by aaniin** [comment]
Dear @AllaMaevskaya,

This fix by Raymond is needed for root6 compilation. I came up with the same fix independently, the commit is sane. Can you please give a +1?!

Cheers,
Hans

**Comment by akubera** [comment]
+1

**Comment by aaniin** [comment]
Dear @pzhristov ,

Can you give a +1 here? AliRoot compilation is broken with root6.

Best,
Hans

**Comment by AllaMaevskaya** [comment]
I am sorry, i will do it.

I skipped your mails. I fixed it and now i need new pull request?

**Comment by aaniin** [comment]
Dear @AllaMaevskaya ,

The easiest is if you comment here with 
+1
being your first word nothing else needed from your side. 

Cheers,
Hans

**Comment by aaniin** [comment]
Hi @raymondEhlers ,

Alla opened her own PR here: https://github.com/alisw/AliRoot/pull/383
This PR should be closed.

Cheers,
Hans

**Comment by aaniin** [comment]
Dear @AllaMaevskaya ,

For what concerns the workflow with github:
The idea is that everybody can suggest code changes like Raymond did, but only few responsible persons like you can approve it. This way you, Alla, don't have to code yourself but only review the code. In the end, you have to work less! :) Next time, don't fix the code yourself but just comment with +1 on a pull request to approve code changes. 

Cheers,
Hans

**Comment by dberzano** [comment]
+1

**Comment by dberzano** [comment]
Sorry I have accidentally approved it but now it's closed so it won't be merged.

**Pull request closed without merging**
