### PR TITLE
Adapt the trigger raw digit maker to work with raw stream in DATE format

### PR DESCRIPTION
**Pull request by aiola**
These changes are needed to use this class also to decode the STU data in the DQM framework.
Nothing changes when this class is used for reconstruction using the raw ROOT format.

### CODE REVIEW

**Comment by aiola** [comment]
See discussion in this [JIRA ticket](https://alice.its.cern.ch/jira/browse/EMCAL-40)

**Comment by mfasDa** [comment]
+test

Would be nice if you could have as commit message in case it refers to a JIRA ticket:
"[EMCAL-40] Factor out ..."
With this it makes it easier to keep track of changes.

**Comment by mfasDa** [comment]
Hi @aiola ,

Thanks for the fix. Looks like you forgot the first commit message as well. Could you fix this as well?
Once this is done I will approve it.

Cheers

Markus

**Comment by mfasDa** [comment]
+1

Thanks a lot! Based on previous discussions I approve the PR.

**Pull request merged**
