### PR TITLE
ATO-426: MOVE alilog4bash.sh and utilities.sh AliPhysics->AliRoot

### PR DESCRIPTION
**Pull request by miranov25**
* alilog4bash.sh and utilities.sh - needed for CTests of aliroot
  *  to avoid circular dependency - move for AliPhysics to AliRoot
  *  Agreed already some time ago
* first step: add the code into AliRoot
* next step: removing from AliPhysics once AliRoot release with changes available

### CODE REVIEW

**Comment by miranov25** [comment]
Hallo @mkrzewic, @ktf , @dberzano and @pzhristov

As we discussed yesterday with Peter, I would like to move utilities.sh and alilog4bash.sh from AliPhycis to AliRoot. See pull request description above describing why is it needed.
We discussed this modification some time ago already with Mikolaj and he also agreed.

In case of not obejctions, @pzhristov, can you please approve this pull request.
I have CTests ready for some of STAT classes, which I would like to push next.

Regards
Marian.

**Comment by miranov25** [comment]
+test

**Comment by dberzano** [comment]
Hi @miranov25, @pzhristov, please hold on. The current release validation depends on those scripts. It needs to be adapted first. Once this is done, I have no objection in doing the move (and I assume there will be a specular PR on AliPhysics doing the removal).

@miranov25: did you check whether this change breaks the production QA? (I assume so!)

@mconcas: since you were looking at those scripts, you'd better be aware of this PR.

**Comment by miranov25** [comment]
Hallo @dberzano

For the moment I did not remove scripts from the AliPhysics. 
In transition period - until new release will be created  we will keep both version.
I did not start yet with removal of scripts.
I was testing utilities in the AliPhysics and full suit is still working.
```
[AliPhysics/latest-alicesw] /data/alicesw/sw/BUILD/AliPhysics-latest/AliPhysics $> ctest -R utilitiesTest 
Test project /data/alicesw/sw/BUILD/AliPhysics-latest/AliPhysics
    Start 97: utilitiesTest
1/1 Test #97: utilitiesTest ....................   Passed    0.12 sec
```
You can check full list of checks:
```
ctest -R utilitiesTest --verbose | grep -i "\[.*\]"
e.g
[AliPhysics/latest-alicesw] /data/alicesw/sw/BUILD/AliPhysics-latest/AliPhysics $> ctest -R utilitiesTest --verbose | grep -i "\[SUCCESS\]"
97: [2017-07-12 10:17:44 CEST] [ivanov-laptop] [SUCCESS] test_guessRunData: Year   2012   2012 
97: [2017-07-12 10:17:44 CEST] [ivanov-laptop] [SUCCESS] test_guessRunData: Period   LHC12g   LHC12g /alice/data/2012/LHC12g/000188362/cpass1_tpc_validation/OCDB/spaceMap_4_4 
97: [2017-07-12 10:17:44 CEST] [ivanov-laptop] [SUCCESS] test_guessRunData: Run   188362   188362 
97: [2017-07-12 10:17:44 CEST] [ivanov-laptop] [SUCCESS] test_guessPassData: Pass   cpass1_tpc_validation   cpass1_tpc_validation 
97: [2017-07-12 10:17:44 CEST] [ivanov-laptop] [SUCCESS] test_guessRunData: Year   2012   2012 
97: [2017-07-12 10:17:44 CEST] [ivanov-laptop] [SUCCESS] test_guessRunData: Period   LHC12a   LHC12a alien:///alice/data/2012/LHC12a/000177011/cpass0_tpc_validation/OCDB/meanITSVertex.root 
97: [2017-07-12 10:17:44 CEST] [ivanov-laptop] [SUCCESS] test_guessRunData: Run   177011   177011 
97: [2017-07-12 10:17:44 CEST] [ivanov-laptop] [SUCCESS] test_guessPassData: Pass   cpass0_tpc_validation   cpass0_tpc_validation 
....

I can put there test for the TPC.QA to test suit so we can easily automatically check.
I was doing this test in the TPC git. I can move code to AliPhysics.

In case you consider this test to be blocker, I will integrate QA test into AliPhysics test suit.
Anyway it is needed.

Marian

**Comment by dberzano** [comment]
Hi @miranov25, ok thanks for testing, it's fine. Let me quickly change the release validation in order to try to get the files from AliRoot first, and then fall back on AliPhysics, so that everybody will be happy.

I have only one remark.

* Normally, binaries/executables are installed under `bin`: those are the executables meant to be launched directly.
* Support executables (_i.e._ scripts to be sourced, or executables not meant to be launched directly by the users), should not have executable permissions, and should be installed under `libexec`, that's a UNIX convention.

Do you mind changing the destination installation to `libexec` for such scripts? Thanks!

**Comment by miranov25** [comment]
@dberzano 
I do not mind moving scripts form lib  to libexec.
Should I do the modification?

**Comment by dberzano** [comment]
Yes please :-)

**Comment by dberzano** [comment]
It's all fine, many thanks! I'll do the change on the relval ASAP, I am working on it.

**Comment by dberzano** [comment]
+1

**Comment by miranov25** [comment]
@dberzano. 
Thank you. 
I will update my aliPhysics.
If i understand correctly I should start removing of the utilities and alilog4bash from AliPhysics
Is it correct?

**Comment by dberzano** [comment]
Yes, go for it! :-)

**Pull request merged**
