### PR TITLE
Added Omega(2012) to AliMC.cxx

### PR DESCRIPTION
**Pull request by aknospe**

### CODE REVIEW

**Comment by chiarazampolli** [comment]
+test

**Comment by chiarazampolli** [comment]
@ihrivnac , @amorsch , can you confirm that the implementation is ok?
I did "+test", but I guess the CI will fail like PR1170, due to some unrelated issues in G4 tests.

Chiara

**Comment by chiarazampolli** [comment]
+1

**Comment by ihrivnac** [comment]
@aknospe , 

Could you update your branch with a dummy commit; eg. add a space in the added comment line to trigger a new build and test the fix (https://github.com/alisw/alidist/pull/2338) for Geant4 ?

Thanks,

**Comment by chiarazampolli** [comment]
Hello @ihrivnac , 

A dummy commit was not needed, the tests were re-run automatically, and after your fix, they passed, so I am approving now, following the discussion at the S&C meeting today (@amorsch confirmed that they are ok). 

@aknospe , for safety, you ran some tests with these changes, right?

Chiara

**Comment by chiarazampolli** [comment]
+1

**Pull request merged**
