### PR TITLE
Update AliTPythia8.cxx

### PR DESCRIPTION
**Pull request by arossi81**
Updating Xic0 lifetime

### CODE REVIEW

**Comment by gconesab** [comment]
Hi @chiarazampolli or @pzhristov,
can any of you approve and merge so that I can cherry-pick it? Thanks.

**Comment by chiarazampolli** [comment]
+1

**Comment by gconesab** [comment]
The build error seems unrelated, can this be merged directly?

**Comment by gconesab** [comment]
Hi @TimoWilken,

can you merge this commit? Thanks!

**Pull request merged**
