### PR TITLE
[ALIROOT-8237] Fix: suppressed event NPart should not be accounted

### PR DESCRIPTION
**Pull request by shahor02**

### CODE REVIEW

**Comment by shahor02** [comment]
This should override https://github.com/alisw/AliRoot/pull/1032

**Comment by shahor02** [comment]
+1

**Comment by miweberSMI** [comment]
Hi @shahor02,

can you check again that this works? It seems to me that wrong generator indices are assigned like that (this is why I had the 2 before).

Collection name='TList', class='TList', size=8
 OBJ: AliGenEventHeader	pizero_0	Event Header
 OBJ: AliGenEventHeader	eta_1	Event Header
 OBJ: AliGenEventHeader	etaprime_2	Event Header
 OBJ: AliGenEventHeader	rho_3	Event Header
 OBJ: AliGenEventHeader	omega_4	Event Header
 OBJ: AliGenEventHeader	phi_5	Event Header
 OBJ: AliGenEventHeader	jpsi_6	Event Header
 OBJ: AliGenHijingEventHeader	Hijing	Event Header_particles_suppressed

But then

Track 0, Particle 7
Generator Index = 0
Mother: 221 eta

Track 1, Particle 9
Generator Index = 1
Mother: 331 etaprime

Track 3, Particle 15
Generator Index = 2
Mother: 113 rho

Track 4, Particle 6
Generator Index = 0
Mother: 221 eta

Track 6, Particle 11
Generator Index = 1
Mother: 331 etaprime

Track 7, Particle 10
Generator Index = 1
Mother: 331 etaprime


Thanks and cheers,
Michael

**Comment by shahor02** [comment]
Hi @miweberSMI 

This is a problem not of the embedding/filtering but of the generator: the sum of NProduced from all generator headers is less than the number of registered primaries in the AliStack of embedded event.
And their difference is not always 2 (which inspired your correction) but can be more.
Looks like the problem is in the J/psi generator.
Below is the dump of the assignments (note the "recovery" message when processing the GenHeader 0: ``Headers inconsistent...``):
````Assigning generator index for 26 primaries
GenHeader 7 of 7, nPart= 9816 | Hijing Event Header_particles_suppressed
Primaries remaining: 26
GenHeader 6 of 7, nPart= 1 | jpsi_6 Event Header
Assign gener.code 6 to prim. 25 (e-) [Parent: 23 Daught: 26-32], XYZ:+9.294e-02 +3.670e-01 +3.295e+00 -1.379e-10
Primaries remaining: 25
GenHeader 5 of 7, nPart= 3 | phi_5 Event Header
Assign gener.code 5 to prim. 24 (e+) [Parent: 23 Daught: 36-39], XYZ:+9.294e-02 +3.670e-01 +3.295e+00 -1.379e-10
Assign gener.code 5 to prim. 23 (J/psi) [Parent: -1 Daught: 24-25], XYZ:+9.294e-02 +3.670e-01 +3.295e+00 -1.379e-10
Assign gener.code 5 to prim. 22 (e-) [Parent: 20 Daught: 49-52], XYZ:+9.294e-02 +3.670e-01 +3.295e+00 -1.379e-10
Primaries remaining: 22
GenHeader 4 of 7, nPart= 4 | omega_4 Event Header
Assign gener.code 4 to prim. 21 (e+) [Parent: 20 Daught: 61-63], XYZ:+9.294e-02 +3.670e-01 +3.295e+00 -1.379e-10
Assign gener.code 4 to prim. 20 (phi) [Parent: -1 Daught: 21-22], XYZ:+9.294e-02 +3.670e-01 +3.295e+00 -1.379e-10
Assign gener.code 4 to prim. 19 (e-) [Parent: 16 Daught: -1--1], XYZ:+9.294e-02 +3.670e-01 +3.295e+00 -1.379e-10
Assign gener.code 4 to prim. 18 (e+) [Parent: 16 Daught: 77-79], XYZ:+9.294e-02 +3.670e-01 +3.295e+00 -1.379e-10
Primaries remaining: 18
GenHeader 3 of 7, nPart= 3 | rho_3 Event Header
Assign gener.code 3 to prim. 17 (pi0) [Parent: 16 Daught: 81-82], XYZ:+9.294e-02 +3.670e-01 +3.295e+00 -1.379e-10
Assign gener.code 3 to prim. 16 (omega) [Parent: -1 Daught: 17-19], XYZ:+9.294e-02 +3.670e-01 +3.295e+00 -1.379e-10
Assign gener.code 3 to prim. 15 (e-) [Parent: 13 Daught: 85-100], XYZ:+9.294e-02 +3.670e-01 +3.295e+00 -1.379e-10
Primaries remaining: 15
GenHeader 2 of 7, nPart= 5 | etaprime_2 Event Header
Assign gener.code 2 to prim. 14 (e+) [Parent: 13 Daught: 280-281], XYZ:+9.294e-02 +3.670e-01 +3.295e+00 -1.379e-10
Assign gener.code 2 to prim. 13 (rho0) [Parent: -1 Daught: 14-15], XYZ:+9.294e-02 +3.670e-01 +3.295e+00 -1.379e-10
Assign gener.code 2 to prim. 12 (e-) [Parent: 8 Daught: 283-289], XYZ:+9.294e-02 +3.670e-01 +3.295e+00 -1.379e-10
Assign gener.code 2 to prim. 11 (e+) [Parent: 8 Daught: 295-300], XYZ:+9.294e-02 +3.670e-01 +3.295e+00 -1.379e-10
Assign gener.code 2 to prim. 10 (pi-) [Parent: 8 Daught: 311-316], XYZ:+9.294e-02 +3.670e-01 +3.295e+00 -1.379e-10
Primaries remaining: 10
GenHeader 1 of 7, nPart= 4 | eta_1 Event Header
Assign gener.code 1 to prim. 9 (pi+) [Parent: 8 Daught: 321-327], XYZ:+9.294e-02 +3.670e-01 +3.295e+00 -1.379e-10
Assign gener.code 1 to prim. 8 (eta') [Parent: -1 Daught: 9-12], XYZ:+9.294e-02 +3.670e-01 +3.295e+00 -1.379e-10
Assign gener.code 1 to prim. 7 (e-) [Parent: 4 Daught: 328-329], XYZ:+9.294e-02 +3.670e-01 +3.295e+00 -1.379e-10
Assign gener.code 1 to prim. 6 (e+) [Parent: 4 Daught: 330-336], XYZ:+9.294e-02 +3.670e-01 +3.295e+00 -1.379e-10
Primaries remaining: 6
GenHeader 0 of 7, nPart= 4 | pizero_0 Event Header
Headers inconsistent !     4 from header     6 remaining, assigning all to generator 0
Assign gener.code 0 to prim. 5 (gamma) [Parent: 4 Daught: 339-340], XYZ:+9.294e-02 +3.670e-01 +3.295e+00 -1.379e-10
Assign gener.code 0 to prim. 4 (eta) [Parent: -1 Daught: 5-7], XYZ:+9.294e-02 +3.670e-01 +3.295e+00 -1.379e-10
Assign gener.code 0 to prim. 3 (e-) [Parent: 0 Daught: 369-376], XYZ:+9.292e-02 +3.670e-01 +3.295e+00 -1.379e-10
Assign gener.code 0 to prim. 2 (e+) [Parent: 0 Daught: 392-394], XYZ:+9.292e-02 +3.670e-01 +3.295e+00 -1.379e-10
Assign gener.code 0 to prim. 1 (gamma) [Parent: 0 Daught: 400-401], XYZ:+9.292e-02 +3.670e-01 +3.295e+00 -1.379e-10
Assign gener.code 0 to prim. 0 (pi0) [Parent: -1 Daught: 1-3], XYZ:+9.294e-02 +3.670e-01 +3.295e+00 -1.379e-10
Primaries remaining: 0
````
As you can see, the J/psi gen. header declares just 1 added particle, but it should have declared 3 for the J/psi itself (id=23) and its daughter e+e- (24 and 25). This creates a shift of 2 in this event.

Here is another event with shift=4:
````
Assigning generator index for 30 primaries
GenHeader 7 of 7, nPart= 9816 | Hijing Event Header_particles_suppressed_particles_suppressed_particles_suppressed
Primaries remaining: 30
GenHeader 6 of 7, nPart= 1 | jpsi_6 Event Header
Assign gener.code 6 to prim. 29 (gamma) [Parent: 23 Daught: -1--1], XYZT:+9.294e-02 +3.670e-01 +3.295e+00 -1.379e-10
Primaries remaining: 29
GenHeader 5 of 7, nPart= 3 | phi_5 Event Header
Assign gener.code 5 to prim. 28 (gamma) [Parent: 23 Daught: 30-31], XYZT:+9.294e-02 +3.670e-01 +3.295e+00 -1.379e-10
Assign gener.code 5 to prim. 27 (gamma) [Parent: 23 Daught: 32-33], XYZT:+9.294e-02 +3.670e-01 +3.295e+00 -1.379e-10
Assign gener.code 5 to prim. 26 (gamma) [Parent: 23 Daught: -1--1], XYZT:+9.294e-02 +3.670e-01 +3.295e+00 -1.379e-10
Primaries remaining: 26
GenHeader 4 of 7, nPart= 4 | omega_4 Event Header
Assign gener.code 4 to prim. 25 (e-) [Parent: 23 Daught: 37-45], XYZT:+9.294e-02 +3.670e-01 +3.295e+00 -1.379e-10
Assign gener.code 4 to prim. 24 (e+) [Parent: 23 Daught: 49-63], XYZT:+9.294e-02 +3.670e-01 +3.295e+00 -1.379e-10
Assign gener.code 4 to prim. 23 (J/psi) [Parent: -1 Daught: 24-29], XYZT:+9.294e-02 +3.670e-01 +3.295e+00 -1.379e-10
Assign gener.code 4 to prim. 22 (e+) [Parent: 20 Daught: 109-115], XYZT:+9.294e-02 +3.670e-01 +3.295e+00 -1.379e-10
Primaries remaining: 22
GenHeader 3 of 7, nPart= 3 | rho_3 Event Header
Assign gener.code 3 to prim. 21 (e-) [Parent: 20 Daught: 119-125], XYZT:+9.294e-02 +3.670e-01 +3.295e+00 -1.379e-10
Assign gener.code 3 to prim. 20 (phi) [Parent: -1 Daught: 21-22], XYZT:+9.294e-02 +3.670e-01 +3.295e+00 -1.379e-10
Assign gener.code 3 to prim. 19 (e-) [Parent: 16 Daught: 129-134], XYZT:+9.294e-02 +3.670e-01 +3.295e+00 -1.379e-10
Primaries remaining: 19
GenHeader 2 of 7, nPart= 5 | etaprime_2 Event Header
Assign gener.code 2 to prim. 18 (e+) [Parent: 16 Daught: -1--1], XYZT:+9.294e-02 +3.670e-01 +3.295e+00 -1.379e-10
Assign gener.code 2 to prim. 17 (pi0) [Parent: 16 Daught: 145-146], XYZT:+9.294e-02 +3.670e-01 +3.295e+00 -1.379e-10
Assign gener.code 2 to prim. 16 (omega) [Parent: -1 Daught: 17-19], XYZT:+9.294e-02 +3.670e-01 +3.295e+00 -1.379e-10
Assign gener.code 2 to prim. 15 (e-) [Parent: 13 Daught: 148-157], XYZT:+9.294e-02 +3.670e-01 +3.295e+00 -1.379e-10
Assign gener.code 2 to prim. 14 (e+) [Parent: 13 Daught: 180-181], XYZT:+9.294e-02 +3.670e-01 +3.295e+00 -1.379e-10
Primaries remaining: 14
GenHeader 1 of 7, nPart= 4 | eta_1 Event Header
Assign gener.code 1 to prim. 13 (rho0) [Parent: -1 Daught: 14-15], XYZT:+9.294e-02 +3.670e-01 +3.295e+00 -1.379e-10
Assign gener.code 1 to prim. 12 (e-) [Parent: 8 Daught: -1--1], XYZT:+9.294e-02 +3.670e-01 +3.295e+00 -1.379e-10
Assign gener.code 1 to prim. 11 (e+) [Parent: 8 Daught: 183-186], XYZT:+9.294e-02 +3.670e-01 +3.295e+00 -1.379e-10
Assign gener.code 1 to prim. 10 (pi-) [Parent: 8 Daught: 187-190], XYZT:+9.294e-02 +3.670e-01 +3.295e+00 -1.379e-10
Primaries remaining: 10
GenHeader 0 of 7, nPart= 4 | pizero_0 Event Header
Headers inconsistent !     4 from header    10 remaining, assigning all to generator 0
Assign gener.code 0 to prim. 9 (pi+) [Parent: 8 Daught: 200-204], XYZT:+9.294e-02 +3.670e-01 +3.295e+00 -1.379e-10
Assign gener.code 0 to prim. 8 (eta') [Parent: -1 Daught: 9-12], XYZT:+9.294e-02 +3.670e-01 +3.295e+00 -1.379e-10
Assign gener.code 0 to prim. 7 (e-) [Parent: 4 Daught: 232-236], XYZT:+9.294e-02 +3.670e-01 +3.295e+00 -1.379e-10
Assign gener.code 0 to prim. 6 (e+) [Parent: 4 Daught: 239-242], XYZT:+9.294e-02 +3.670e-01 +3.295e+00 -1.379e-10
Assign gener.code 0 to prim. 5 (gamma) [Parent: 4 Daught: 245-246], XYZT:+9.294e-02 +3.670e-01 +3.295e+00 -1.379e-10
Assign gener.code 0 to prim. 4 (eta) [Parent: -1 Daught: 5-7], XYZT:+9.294e-02 +3.670e-01 +3.295e+00 -1.379e-10
Assign gener.code 0 to prim. 3 (e-) [Parent: 0 Daught: 247-250], XYZT:+9.295e-02 +3.670e-01 +3.295e+00 -1.379e-10
Assign gener.code 0 to prim. 2 (e+) [Parent: 0 Daught: 253-254], XYZT:+9.295e-02 +3.670e-01 +3.295e+00 -1.379e-10
Assign gener.code 0 to prim. 1 (gamma) [Parent: 0 Daught: 260-261], XYZT:+9.295e-02 +3.670e-01 +3.295e+00 -1.379e-10
Assign gener.code 0 to prim. 0 (pi0) [Parent: -1 Daught: 1-3], XYZT:+9.294e-02 +3.670e-01 +3.295e+00 -1.379e-10
Primaries remaining: 0
````
Again, J/psi header declare 1 particle added while it added to the stack 5 particles, 23-29.

I see in the https://github.com/alisw/AliDPG/blob/f074cd84608f8db50720751ec782d49abe765d38/MC/CustomGenerators/PWGDQ/Hijing_LMee001.C#L137 the line ``jpsi->SetForceDecay(kNoDecay);``
followed by ``AliGenEvtGen *gene = new AliGenEvtGen();`` which is supposed to perform decays of particles from other generators (and it does not appear in the list of generators in the galice). I suspect it decays the J/psi, adds its products but this is not reflected in any of the generator headers.

Cheers,
 Ruben

**Comment by miweberSMI** [comment]
Hi @shahor02 ,

your comments are perfectly correct (we are using EvtGen to decay JPsi as requested by @dsekihat and suggested by @tdahms and @ffionda). But do I understand correctly that the particles from teh same generator get always the same index, tehy are just shifted by one in this case? Then I think for our production it should still work out...

Thanks and cheers,
Michael

**Comment by shahor02** [comment]
Hi @miweberSMI 

No, unfortunately one cannot have correct gen.index assignment with this schema: if out of N primaries there are M particles which are not accounted in the generator header (because they were added by the EvtGen), then starting from the N-M-th particle the assignment might be shifted. In the example of my prev. message the mother particle created by the generator is always assigned wrong gen. index, except the particles from the 1st generator: it is treated in the very end and absorbs its own particle + M unaccounted ones. 

Why J/psi cannot be decayed within its own generator?

Cheers,
 Ruben

**Comment by miweberSMI** [comment]
Hi @shahor02,

argh... ;)
We wanted to have this for the radiative JPsi decay and apparently it was doen like that already by other groups (this is why I added @tdahms and @ffionda ).

Cheers,
Michael

**Comment by shahor02** [comment]
Hi @miweberSMI 
The only way I see to have the EvtGen compatible with the AssignGeneratorIndex algorithm is to
(1) in the configuration add it after every real generator (which potentially can add undecayed particles, in this particular job this was not a case so it is enough to have it after the J/psi generator only).
This is needed to guarantee that the decay product follow parents in the stack, so they can be assigned the same gen. index.
(2) EvtGen, after adding decay products to the stack should increment the NParticles of the previous generator.

The alternative would be to force EvtGen to add its own gen. header to the MC header, where all decay products would be accounted. Obviously, these decay products would get the  EvtGen gen. index assigned, but at least their parents would get correct gen.index and the original generator for decay products can be correctly traced back.

Cheers,
 Ruben

**Comment by ffionda** [comment]
Dear Ruben, Michael,
I think this is correct, AliGenEvtGen is not added to the list of generators and the decay products of undecayed particles from "true" generators are simply added to the stack (that's why we always add EvtGen after all other generators, as you also mentioned, in order to have the decay products after parents particles in the stack). But just to be sure I understood correctly: the problem is just that you cannot use GetGeneratorIndex to identify the injected signals (because it's not assigned correctly), but there's no other issue with the simulation itself, right ?  (E.g. for jpsi analyses we don't use the generator index, we identify prompt and non-prompt signals looking at the corresponding parents in the decay chains, and the assignment of daughters / parents indices in the stack is done correctly). 
Thank you,
Regards
Fiorella

**Comment by shahor02** [comment]
Hi @ffionda , all

Right, the simulation itself is correct, but note that AliGenEvtGen makes incorrect the assignment of not only J/psi and its product's generator indices: almost all primaries get incorrect generator index so it cannot be used for such productions.

Cheers,
 Ruben

**Pull request merged**
