### PR TITLE
Modifications to Ali[]Vertexer classes

### PR DESCRIPTION
**Pull request by ddobrigk**
see https://indico.cern.ch/event/699851/

### CODE REVIEW

**Comment by chiarazampolli** [comment]
Ciao David,

Is this ready to be merged?

Chiara

**Comment by ddobrigk** [comment]
Ciao Chiara, 

Not yet: I managed to screw it up just now, sorry. Give me a moment, am fixing it now... 

Cheers,
David

**Comment by ddobrigk** [comment]
+test

**Comment by shahor02** [comment]
+test (no...:()

**Comment by ddobrigk** [comment]
sigh... now I think my merge canceled the testing. Sorry... Could somebody re-issue the +test?

**Comment by shahor02** [comment]
+test

**Comment by shahor02** [comment]
@ddobrigk shall I merge already?

**Comment by ddobrigk** [comment]
@shahor02, yes, please, go ahead! I will still test a bit more but everything seems to be fine.

**Comment by shahor02** [comment]
+1

**Pull request merged**
