### PR TITLE
ALIROOT-6527, ALIROOT-5727: Bug fix: alihadd max size switch. 

### PR DESCRIPTION
**Pull request by miranov25**
###  ALIROOT-6527, ALIROOT-5727: Bug fix: alihadd max size switch ￼…
* initialize  cost in costructor in struct MergeJob
* object size - add  ZipBytes in case of TTree
* reset counter in case splitted
* set logic in logs according documantation
  * to fix default logging as now it is too verbose

### Cosmetic changes in the AliExternalInfo and tests
* USE: tee in tests
* ADD: print comman in verbose mode

### CODE REVIEW

**Comment by miranov25** [comment]
Hallo @ktf 

I implemented  several bug fixes in the alihadd related to splitting files
See first part of the commit measage
Related to ALIROOT-6527, ALIROOT-5727.

As next step I would like to proceed with alihadd.sh and alihadd.jdl as we planned 2 years ago but we did not manage.   Main motivation for this development were recent problem with merging of the FilteredTress.

To follow:
* force check  mode  - checking input data for corrupted files 
  * see Add:AliXRDPROOFtoolkit::TestFile - https://github.com/alisw/AliRoot/pull/307
  * merge only validated files (read/write/delete/copy test)
  * prepare a list of corrupted files
* validate other features of alihadd
* alihadd.sh 
  * <filtering> + alihadd
  * To AliPhysics/script/utilities  or STEER/Utilities

**Comment by miranov25** [comment]
To speed up approval:
* can you confirm you received massage 
* Bug fixes which I fixed were real bugs
* There are currently not default test were i can prove that change was necessary
* To follow part we can discuss after approval of the bug fix
* Can I get rights for STEER/Utilities

**Comment by miranov25** [comment]
I would like to unblock my repository
Is somebody looking to the pull request?

**Comment by ktf** [comment]
+test

**Comment by miranov25** [comment]
thank you

**Pull request merged**
