### PR TITLE
Additional protection, needed for FLUKA

### PR DESCRIPTION
**Pull request by fprino**

### CODE REVIEW

**Comment by pzhristov** [comment]
+1

**Comment by ktf** [comment]
@TimoWilken AliRoot/release seems stuck...

**Comment by TimoWilken** [comment]
@ktf `git ls-remote --heads https://github.com/google/benchmark` got stuck, it's been doing nothing since 06:38 this morning. I've killed it, it's now working again.

That stuck git command was running under the main aliBuild command, which has a 10h timeout -- which is why it wasn't killed earlier.

**Comment by ktf** [comment]
Ok. We should add a per command timeout to all those in alibuild.

**Pull request merged**
