### PR TITLE
testing commit to my fork

### PR DESCRIPTION
**Pull request by jgrosseo**
and here we go!

### CODE REVIEW

**Comment by qgp** [comment]
+1

**Comment by ktf** [comment]
@jgrosseo @qgp this reminds me we should discuss what we want to test. Right now I also run the "gun" test, but I assume we should have a more basic test for compilation, at least to start with. What do you think?

**Comment by ktf** [comment]
+test

**Comment by ktf** [comment]
@dberzano how about "testing approved, merging will require further approval by X, Y, Z; starting tests."

**Comment by dberzano** [comment]
@ktf I agree, that's nicer.

**Comment by qgp** [comment]
+1

**Comment by jgrosseo** [comment]
@dberzano @ktf What is going to happen next? It should merge, right?

**Comment by dberzano** [comment]
Since the approver replied with `+tests` instead of `+1` then no.

**Comment by jgrosseo** [comment]
@qgp just approved, didn't he?

**Comment by jgrosseo** [comment]
@dberzano any comment?

**Comment by dberzano** [comment]
@jgrosseo: the pull requests checker is not running (we are working on it now and we will tell when's ready) - @qgp said "+1" to the comment above, I guess, and in any case he has no permission to approve the merging (look at the last comment requiring me or Giulio to approve, the first one including Jochen belongs to a different permission set).

**Comment by jgrosseo** [comment]
@dberzano Thanks! I overlooked that @ggp was not in the list.

**Comment by dberzano** [comment]
I guess you have tagged the wrong GitHub user instead of @qgp :-)

**Pull request closed without merging**
