### PR TITLE
Include fCorrFuncSlope and fCorrFuncCurv in destructor

### PR DESCRIPTION
**Pull request by MartinSchmidtTuebingen**

### CODE REVIEW

**Comment by wiechula** [comment]
@dberzano : Despite Chiara's approval this is not merged, yet. Is there a problem with the system?

**Comment by chiarazampolli** [comment]
I can try again...

**Comment by chiarazampolli** [comment]
I think it does not work...

**Comment by chiarazampolli** [comment]
+1

**Pull request merged**
