### PR TITLE
Decayer configurations for eta prime MC generator

### PR DESCRIPTION
**Pull request by fkellere**

### CODE REVIEW

**Comment by chiarazampolli** [comment]
To me it looks fine, approving it.

**Comment by chiarazampolli** [comment]
+1

**Comment by fkellere** [comment]
Hey can you please approve this for a second time? Seems it needs a second one

**Comment by chiarazampolli** [comment]
Dear @qgp , @shahor02, can you check and approve?

Thanks!

Chiara

**Comment by shahor02** [comment]
+1

**Pull request merged**
