### PR TITLE
Sync AliGPU from O2

### PR DESCRIPTION
**Pull request by davidrohr**

### CODE REVIEW

**Comment by davidrohr** [comment]
+test

**Comment by davidrohr** [comment]
@TimoWilken @MichaelLettrich : The MacCI seems to fail here without showing a real error.

**Comment by TimoWilken** [comment]
It looks to me like the error mentioned in the HTML log (`error: 'auto' return without trailing return type; deduced return types are a C++14 extension`) is the one that killed the build.

On a separate note, I'm not sure why the AliRoot log isn't last in the plain-text log -- it is the last thing that was built, and the build error occurred during AliRoot compilation.

**Comment by davidrohr** [comment]
ah, ok, thanks. I was only looking at the last log. Indeed, the sorting is wrong.

**Comment by davidrohr** [comment]
+test

**Comment by davidrohr** [comment]
+test

**Comment by davidrohr** [comment]
+test

**Comment by davidrohr** [comment]
+1

**Pull request merged**
